package com.codexdemo.orderplatform.ops;

import java.util.List;

public record OpsShardReadinessRuntimeExecutionApprovalInputTemplateCompatibilityResponse(
        String project,
        String version,
        boolean readOnly,
        boolean executionAllowed,
        boolean templateCompatibilityReceiptPresent,
        boolean templateCompatibilityReceiptComplete,
        boolean sourceContractHandoffPresent,
        boolean sourceJavaInputCanonical,
        boolean nodeTemplateValidatorPresent,
        boolean templatesAreApprovalInputs,
        boolean canonicalApprovalInputsCreatedByJava,
        boolean runtimeGateApprovalPresent,
        boolean nodeApprovedRuntimeWindowPresent,
        boolean correlatedOperatorApprovalRecordPresent,
        boolean completeCrossProjectRuntimeExecutionPacketPresent,
        boolean crossProjectRuntimeExecutionPacketExecutable,
        boolean readyForRuntimeExecutionPacket,
        boolean readyForRuntimeLiveReadGate,
        boolean executionAttempted,
        boolean startsJavaService,
        boolean startsMiniKvService,
        boolean activeShardPrototypeEnabled,
        String sourceContractHandoffVersion,
        String sourceCanonicalJavaInputVersion,
        String lastTemplateValidatorNodeVersion,
        String nextNodeConsumerHint,
        String receiptScope,
        String receiptId,
        String canonicalJavaApprovalInputPath,
        String canonicalJavaApprovalInputEndpoint,
        String canonicalJavaApprovalInputFixture,
        List<String> templateMatrix,
        List<String> canonicalTargetPaths,
        List<String> templateArchivePaths,
        List<String> javaTemplateBindingFields,
        List<String> compatibilityChecks,
        List<String> blockedCanonicalInputs,
        List<String> failClosedRules,
        List<String> stopConditions,
        String evidencePath,
        String status
) {
}
