package com.codexdemo.orderplatform.ops;

import java.util.List;
import java.util.function.Supplier;

final class ReleaseApprovalVerificationHintContributionCatalog {

    private ReleaseApprovalVerificationHintContributionCatalog() {
    }

    static List<ReleaseApprovalVerificationHintContribution> build(
            ReleaseApprovalManagedAuditSandboxAdapterApprovalSchemaGuardReceiptBuilder
                    sandboxAdapterApprovalSchemaGuardReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionOperatorHandoffMarkerBuilder
                    sandboxConnectionOperatorHandoffMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionPreflightEchoMarkerBuilder
                    sandboxConnectionPreflightEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionPreconditionReceiptBuilder
                    sandboxConnectionPreconditionReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionDryRunEnvelopeEchoReceiptBuilder
                    sandboxConnectionDryRunEnvelopeEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionOperatorWindowChecklistEchoReceiptBuilder
                    sandboxConnectionOperatorWindowChecklistEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionDryRunCommandPackageEchoReceiptBuilder
                    sandboxConnectionDryRunCommandPackageEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionPrecheckPacketEchoReceiptBuilder
                    sandboxConnectionPrecheckPacketEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder
                    sandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder
                    sandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointHandlePreflightEchoMarkerBuilder
                    sandboxEndpointHandlePreflightEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverDecisionEchoMarkerBuilder
                    sandboxEndpointCredentialResolverDecisionEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder
                    sandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder
                    sandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder
                    sandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder
                    sandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder
                    sandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder
                    sandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder
                    sandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder
                    sandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder
                    sandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder
                    sandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder
                    sandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder
                    sandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder
                    sandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder
                    sandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder
                    sandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder
                    sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder
                    sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder
                    sandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder
                    sandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder,
            ReleaseApprovalManagedAuditSandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
                    sandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
    ) {
        return List.of(
                contribution(
                        sandboxAdapterApprovalSchemaGuardReceiptBuilder::warningDigestWarningInputNames,
                        sandboxAdapterApprovalSchemaGuardReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxAdapterApprovalSchemaGuardReceiptBuilder::proofClaims,
                        () -> sandboxAdapterApprovalSchemaGuardReceiptBuilder.nodeVerificationActions().stream()
                                .filter(action -> !("Verify managedAuditSandboxAdapterApprovalSchemaGuardReceipt"
                                        + ".qualityGateBoundary.builderOrHelperSplitApplied=true").equals(action))
                                .toList()
                ),
                contribution(sandboxConnectionOperatorHandoffMarkerBuilder::warningDigestWarningInputNames,
                        sandboxConnectionOperatorHandoffMarkerBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionOperatorHandoffMarkerBuilder::proofClaims,
                        sandboxConnectionOperatorHandoffMarkerBuilder::nodeVerificationActions),
                contribution(sandboxConnectionPreflightEchoMarkerBuilder::warningDigestWarningInputNames,
                        sandboxConnectionPreflightEchoMarkerBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionPreflightEchoMarkerBuilder::proofClaims,
                        sandboxConnectionPreflightEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxConnectionPreconditionReceiptBuilder::warningDigestWarningInputNames,
                        sandboxConnectionPreconditionReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionPreconditionReceiptBuilder::proofClaims,
                        sandboxConnectionPreconditionReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionDryRunEnvelopeEchoReceiptBuilder::warningDigestWarningInputNames,
                        sandboxConnectionDryRunEnvelopeEchoReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionDryRunEnvelopeEchoReceiptBuilder::proofClaims,
                        sandboxConnectionDryRunEnvelopeEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionOperatorWindowChecklistEchoReceiptBuilder::warningDigestWarningInputNames,
                        sandboxConnectionOperatorWindowChecklistEchoReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionOperatorWindowChecklistEchoReceiptBuilder::proofClaims,
                        sandboxConnectionOperatorWindowChecklistEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionDryRunCommandPackageEchoReceiptBuilder::warningDigestWarningInputNames,
                        sandboxConnectionDryRunCommandPackageEchoReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionDryRunCommandPackageEchoReceiptBuilder::proofClaims,
                        sandboxConnectionDryRunCommandPackageEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionPrecheckPacketEchoReceiptBuilder::warningDigestWarningInputNames,
                        sandboxConnectionPrecheckPacketEchoReceiptBuilder::warningDigestBoundaryInputNames,
                        sandboxConnectionPrecheckPacketEchoReceiptBuilder::proofClaims,
                        sandboxConnectionPrecheckPacketEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder::proofClaims,
                        sandboxConnectionDisabledAdapterClientPrecheckEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder
                                ::warningDigestWarningInputNames,
                        sandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder::proofClaims,
                        sandboxConnectionFakeTransportDryRunPacketEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxEndpointHandlePreflightEchoMarkerBuilder::warningDigestWarningInputNames,
                        sandboxEndpointHandlePreflightEchoMarkerBuilder::warningDigestBoundaryInputNames,
                        sandboxEndpointHandlePreflightEchoMarkerBuilder::proofClaims,
                        sandboxEndpointHandlePreflightEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverDecisionEchoMarkerBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverDecisionEchoMarkerBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverDecisionEchoMarkerBuilder::proofClaims,
                        sandboxEndpointCredentialResolverDecisionEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder::proofClaims,
                        sandboxEndpointCredentialResolverDisabledPrecheckEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder::proofClaims,
                        sandboxEndpointCredentialResolverTestOnlyShellEchoMarkerBuilder::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder::proofClaims,
                        sandboxEndpointCredentialResolverFakeShellArchiveEchoReceiptBuilder::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder::proofClaims,
                        sandboxEndpointCredentialResolverProductionReadinessBlockedDecisionEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder::proofClaims,
                        sandboxEndpointCredentialResolverPreImplementationPlanIntakeEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder::proofClaims,
                        sandboxEndpointCredentialResolverDisabledImplementationCandidateEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverApprovalRequiredImplementationReadinessEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverImplementationPlanEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverExecutionDeniedEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellHandoffEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverDisabledRuntimeShellCandidateGateEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverRuntimeShellDecisionRecordEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverRuntimeShellPostDecisionPlanIntakeEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverRuntimeShellStopPrerequisiteDecisionEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverApprovalPrerequisiteArtifactIntakeEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPacketEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverHumanApprovalArtifactReviewPostEchoDecisionGateEchoReceiptBuilder
                                ::nodeVerificationActions)
                ,
                contribution(sandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverSignedHumanApprovalArtifactContractEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverCredentialHandleApprovalContractEchoReceiptBuilder
                                ::nodeVerificationActions),
                contribution(sandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
                                ::warningDigestWarningInputNames,
                        sandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
                                ::warningDigestBoundaryInputNames,
                        sandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
                                ::proofClaims,
                        sandboxEndpointCredentialResolverEndpointHandleAllowlistApprovalContractEchoReceiptBuilder
                                ::nodeVerificationActions)
        );
    }

    private static ReleaseApprovalVerificationHintContribution contribution(
            Supplier<List<String>> warningDigestWarningInputNames,
            Supplier<List<String>> warningDigestBoundaryInputNames,
            Supplier<List<String>> proofClaims,
            Supplier<List<String>> nodeVerificationActions
    ) {
        return new ReleaseApprovalVerificationHintContribution(
                warningDigestWarningInputNames,
                warningDigestBoundaryInputNames,
                proofClaims,
                nodeVerificationActions
        );
    }
}
