package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class OpsEvidenceServiceReleaseApprovalRehearsalHeaderBackedOverviewTests extends OpsEvidenceServiceRehearsalTestSupport {

    @Test
    void buildsReleaseApprovalRehearsalOverviewForHeaderBackedRequest() {
        OpsEvidenceService service = readOnlyFixtureService();
        ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();

        ReleaseApprovalRehearsalResponse headerBackedRehearsal =
                service.releaseApprovalRehearsal(paddedHeaderBackedRehearsalRequest());
        assertThat(headerBackedRehearsal.requestContext().requestId()).isEqualTo("rehearsal-v67-001");
        assertThat(headerBackedRehearsal.requestContext().requestIdSource())
                .isEqualTo("X-Rehearsal-Request-Id");
        assertThat(headerBackedRehearsal.requestContext().operatorIdentity())
                .isEqualTo("release-operator@example.test");
        assertThat(headerBackedRehearsal.requestContext().operatorIdentitySource())
                .isEqualTo("X-Operator-Identity");
        assertThat(headerBackedRehearsal.requestContext().auditCorrelationId())
                .isEqualTo("audit-correlation-v67");
        assertThat(headerBackedRehearsal.requestContext().auditCorrelationSource())
                .isEqualTo("X-Audit-Correlation-Id");
        assertThat(headerBackedRehearsal.requestContext().contextWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorId()).isEqualTo("operator-198");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdSource())
                .isEqualTo("x-orderops-operator-id");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRoles()).isEqualTo("operator,auditor");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesSource())
                .isEqualTo("x-orderops-roles");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaim()).isEqualTo("true");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimSource())
                .isEqualTo("x-orderops-operator-verified");
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationId())
                .isEqualTo("approval-v198-operator-window");
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationIdSource())
                .isEqualTo("x-orderops-approval-correlation-id");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdentityEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorWindowContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().productionIdpVerifiedByJava()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().persistedApprovalRecordByJava()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().nodeMayTreatAsProductionIdentity()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersion())
                .isEqualTo("real-read-window-ci-archive-artifact-manifest.v1");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionSource())
                .isEqualTo("x-orderops-ci-manifest-version");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigest())
                .isEqualTo("sha256:node-v200-manifest-digest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestSource())
                .isEqualTo("x-orderops-ci-manifest-digest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpoint())
                .isEqualTo("/api/v1/production/real-read-window-ci-archive-artifact-manifest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointSource())
                .isEqualTo("x-orderops-ci-manifest-endpoint");
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCount()).isEqualTo("9");
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountSource())
                .isEqualTo("x-orderops-ci-artifact-record-count");
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationId())
                .isEqualTo("approval-v198-operator-window");
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationIdSource())
                .isEqualTo("x-orderops-ci-approval-correlation-id");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().ciEvidenceContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().noLedgerWriteProved()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().productionWindowAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().nodeMayTreatAsCiArtifactPublication()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersion())
                .isEqualTo("real-read-window-ci-artifact-upload-dry-run-contract.v1");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersionSource())
                .isEqualTo("x-orderops-ci-upload-contract-version");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigest())
                .isEqualTo("sha256:node-v202-upload-contract-digest");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigestSource())
                .isEqualTo("x-orderops-ci-upload-contract-digest");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactName())
                .isEqualTo("orderops-real-read-window-evidence-v191-v201");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactNameSource())
                .isEqualTo("x-orderops-ci-artifact-name");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRoot()).isEqualTo("c/");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRootSource())
                .isEqualTo("x-orderops-ci-artifact-root");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDays()).isEqualTo("30");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDaysSource())
                .isEqualTo("x-orderops-ci-retention-days");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadMode())
                .isEqualTo("dry-run-contract-only");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadModeSource())
                .isEqualTo("x-orderops-ci-upload-mode");
        assertThat(headerBackedRehearsal.artifactRetentionHint().artifactRetentionContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().retentionDaysWithinJavaRetention()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().javaRetentionFixtureReadOnly()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().productionWindowAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().nodeMayTreatAsRetentionAuthorization()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersion())
                .isEqualTo("three-project-real-read-runtime-smoke-preflight.v1");
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersionSource())
                .isEqualTo("x-orderops-runtime-preflight-version");
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigest())
                .isEqualTo("sha256:node-v204-preflight-digest");
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigestSource())
                .isEqualTo("x-orderops-runtime-preflight-digest");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionId())
                .isEqualTo("runtime-smoke-v205-session-001");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionIdSource())
                .isEqualTo("x-orderops-runtime-smoke-session-id");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetId())
                .isEqualTo("java-release-approval-rehearsal");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetIdSource())
                .isEqualTo("x-orderops-runtime-read-target-id");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowMode())
                .isEqualTo("manual-open-window-plan");
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowModeSource())
                .isEqualTo("x-orderops-runtime-window-mode");
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersionEchoed()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigestEchoed()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionIdEchoed()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetIdEchoed()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowModeEchoed()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().liveReadinessContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().readyForRuntimeSmokeRead()).isTrue();
        assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.liveReadinessHint().javaStartedProcessForNode()).isFalse();
        assertThat(headerBackedRehearsal.liveReadinessHint().nodeMayTreatAsProductionAuthorization()).isFalse();
        assertThat(headerBackedRehearsal.liveReadinessHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateVersion())
                .isEqualTo("managed-audit-persistence-boundary-candidate.v1");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateVersionSource())
                .isEqualTo("x-orderops-managed-audit-candidate-version");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateDigest())
                .isEqualTo("sha256:node-v208-managed-audit-candidate-digest");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateDigestSource())
                .isEqualTo("x-orderops-managed-audit-candidate-digest");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditSinkMode())
                .isEqualTo("file-or-sqlite-dry-run-candidate");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditSinkModeSource())
                .isEqualTo("x-orderops-managed-audit-sink-mode");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRetentionDays())
                .isEqualTo("30");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRetentionDaysSource())
                .isEqualTo("x-orderops-managed-audit-retention-days");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRotationPolicy())
                .isEqualTo("size-and-age-rotation-candidate");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRotationPolicySource())
                .isEqualTo("x-orderops-managed-audit-rotation-policy");
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().candidateVersionEchoed()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().candidateDigestEchoed()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().sinkModeEchoed()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().retentionDaysEchoed()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().rotationPolicyEchoed()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().auditPersistenceHandoffContextComplete())
                .isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRetentionWithinJavaRetention())
                .isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaAuditSourceReadOnly()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaLedgerWriteAllowed()).isFalse();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaManagedAuditWriteAllowed()).isFalse();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaExternalAuditSystemAccessed()).isFalse();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().nodeMayUseAsManagedAuditInput()).isTrue();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().nodeMayTreatAsProductionAuditRecord())
                .isFalse();
        assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractVersion())
                .isEqualTo("managed-audit-identity-approval-binding-contract.v1");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractVersionSource())
                .isEqualTo("x-orderops-approval-binding-contract-version");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigest())
                .isEqualTo("sha256:node-v210-approval-binding-digest");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigestSource())
                .isEqualTo("x-orderops-approval-binding-contract-digest");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestId())
                .isEqualTo("approval-request-v210-001");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestIdSource())
                .isEqualTo("x-orderops-approval-request-id");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionState())
                .isEqualTo("APPROVED_DRY_RUN_ONLY");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionStateSource())
                .isEqualTo("x-orderops-approval-decision-state");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationId())
                .isEqualTo("approval-record-correlation-v210");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationIdSource())
                .isEqualTo("x-orderops-approval-record-correlation-id");
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractVersionEchoed())
                .isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigestEchoed())
                .isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestIdEchoed()).isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionStateEchoed()).isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationEchoed()).isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordHandoffContextComplete())
                .isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordFixtureReadOnly()).isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalDecisionCreated()).isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalLedgerWritten()).isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalRecordPersisted()).isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalRecordAuthenticated()).isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().productionApprovalStoreRequired()).isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().nodeMayUseAsAuditApprovalInput()).isTrue();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().nodeMayTreatAsProductionApprovalRecord())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalRecordHandoffHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211HandoffAccepted()).isTrue();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211NoWriteBoundaryAccepted()).isTrue();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().readyForNodeV213RestoreDrillPlan())
                .isTrue();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().markerWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211ProductionAuditRecordAllowed())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211RealApprovalDecisionCreated())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211RealApprovalLedgerWritten())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().javaApprovalRecordPersisted())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeMayTreatAsProductionAuditRecord())
                .isFalse();
        assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().consumedHandoffFieldPaths())
                .contains(
                        "approvalRecordHandoffHint.approvalRecordCorrelationId",
                        "approvalRecordHandoffHint.approvalTimestampPlaceholder",
                        "verificationHint.warningDigest"
                );
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt()
                .readyForNodeV215DryRunAdapterCandidate()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().receiptWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayConsume()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayWriteLocalDryRunFiles())
                .isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayConnectManagedAudit())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayCreateApprovalDecision())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayWriteApprovalLedger())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayPersistApprovalRecord())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayExecuteSql()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayTriggerDeployment())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayTriggerRollback())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayExecuteRestore())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().javaApprovalDecisionCreated())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().javaApprovalLedgerWritten())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().javaApprovalRecordPersisted())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().javaManagedAuditWriteExecuted())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().readyForProductionAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().readyForProductionWindow()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForNodeV217ProductionHardeningReadinessGate()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt().receiptWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .operatorIdentityPrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .approvalDecisionSourcePrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .ledgerHandoffPrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .retentionOwnerPrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .failureHandlingPrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .rollbackReviewPrerequisiteDocumented()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaCreatesApprovalDecision()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaWritesApprovalLedger()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaWritesManagedAuditStore()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt().javaExecutesSql())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaTriggersDeployment()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaTriggersRollback()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .javaExecutesRestore()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayConnectManagedAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayWriteApprovalLedger()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayExecuteSql()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayTriggerDeployment()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayTriggerRollback()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayExecuteRestore()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt().readyForProductionAudit())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt().readyForProductionWindow())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForProductionOperations()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt()
                .readyForNodeV219ImplementationPrecheck()).isTrue();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().receiptWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().nodeV219MayConsume()).isTrue();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().firstSafeSplitApplied()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().broadServiceSplitDeferred()).isTrue();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().apiShapeChanged()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalDecisionCreated()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalLedgerWritten()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalRecordPersisted()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().managedAuditStoreWritten()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().sqlExecuted()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().deploymentTriggered()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().rollbackTriggered()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().restoreExecuted()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().readyForProductionAudit()).isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().readyForProductionWindow())
                .isFalse();
        assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .readyForNodeV221LocalAdapterCandidateDryRun()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .consumedByNodeDisabledShellProfile())
                .isEqualTo("managed-audit-adapter-disabled-shell.v1");
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .nodeV220SelectedAdapterDisabled()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .nodeV220LocalDryRunOnlyDeclared()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().nodeV220AppendWritten())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .nodeV220ExternalManagedAuditAccessed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .nodeV220LocalDryRunWritePerformed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaApprovalDecisionCreated())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaApprovalLedgerWritten())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaApprovalRecordPersisted())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaManagedAuditStoreWritten())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaSqlExecuted())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaDeploymentTriggered())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaRollbackTriggered())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaRestoreExecuted())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().readyForProductionAudit())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().readyForProductionWindow())
                .isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForNodeV223ExternalAdapterConnectionReadinessReview()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .consumedByNodeVerificationReportProfile())
                .isEqualTo("managed-audit-local-adapter-candidate-verification-report.v1");
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222ReadOnlyReport()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222SourceEndpointRerunPerformed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222AdditionalLocalDryRunWritePerformed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222ConnectsManagedAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .ownerApprovalRequiredBeforeConnection()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .schemaMigrationReviewRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .credentialReviewRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .externalManagedAuditConnectionOpened()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .externalManagedAuditSchemaMigrated()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .javaApprovalLedgerWritten()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .javaManagedAuditStoreWritten()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .javaSqlExecuted()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForProductionAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForProductionWindow()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForNodeV225SandboxAdapterDryRunPackage()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt().guardWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .consumedByNodeSandboxPlanProfile())
                .isEqualTo("managed-audit-sandbox-adapter-dry-run-plan.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeV224SandboxPlan().readOnlyPlan()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeV224SandboxPlan().connectsManagedAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .ownerApprovalBoundary().ownerApprovalArtifactRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .ownerApprovalBoundary().ownerApprovalArtifactProvidedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .schemaRehearsalBoundary().schemaMigrationExecutionAllowed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .schemaRehearsalBoundary().schemaMigrationSqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .credentialBoundary().sandboxCredentialHandleRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary().externalManagedAuditConnectionOpened()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary().javaManagedAuditStoreWritten()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary().javaSqlExecuted()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary().builderClassName())
                .isEqualTo("ReleaseApprovalManagedAuditSandboxAdapterApprovalSchemaGuardReceiptBuilder");
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary().builderOrHelperSplitApplied()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary().longBooleanConstructorAvoided()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForProductionAudit()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForProductionWindow()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt().guardDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForNodeV229ManualSandboxConnectionPacketVerification()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketProfile())
                .isEqualTo("managed-audit-manual-sandbox-connection-operator-packet.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary().manualSandboxConnectionWindowRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary().manualSandboxConnectionWindowOpenedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary().connectionExecutionAllowed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary().ownerApprovalArtifactIdFieldRecognizedByJava()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary().schemaRehearsalIdFieldRecognizedByJava()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary().credentialHandleNameRecognizedByJava()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .schemaRehearsalBoundary().schemaMigrationSqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary().rollbackExecutionAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary().externalManagedAuditConnectionOpenedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary().sqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForManagedAuditSandboxAdapterConnection()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForNodeV231ManualSandboxConnectionPreflightVerification()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateProfile())
                .isEqualTo("managed-audit-manual-sandbox-connection-preflight-gate.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary().manualWindowFlagName())
                .isEqualTo("ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary().manualWindowOpenByDefault()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary().manualWindowOpenedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary().nodeAutoStartAllowed()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary().allRequiredPreflightFieldsRecognizedByJava()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary().gateCreatesConnectionCommand()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .schemaRehearsalBoundary().schemaMigrationSqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .rollbackPathBoundary().rollbackExecutionAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary().externalManagedAuditConnectionOpenedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary().sqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForManagedAuditSandboxAdapterConnection()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .nodeMayTreatAsProductionAuditRecord()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker()
                .requiredPreflightFields())
                .containsExactly(
                        "ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID",
                        "ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE",
                        "ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID",
                        "ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID",
                        "timeoutBudgetMs=15000",
                        "ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT",
                        "ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED"
                );
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .readyForNodeV235ManualSandboxConnectionPreconditionIntake()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt().receiptWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .consumedByNodeBlockedExecutionRehearsalProfile())
                .isEqualTo("managed-audit-manual-sandbox-connection-blocked-execution-rehearsal.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .ownerApprovalBoundary().ownerApprovalArtifactRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .credentialBoundary().credentialHandleReviewRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .schemaRehearsalBoundary().schemaMigrationSqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .rollbackPathBoundary().rollbackExecutionAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .javaExecutionBoundary().externalManagedAuditConnectionOpenedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .javaExecutionBoundary().actualConnectionAttemptedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt()
                .readyForManagedAuditSandboxAdapterConnection()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionPreconditionReceipt().receiptDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .readyForNodeV237ManualSandboxConnectionReadinessGate()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt().receiptWarnings())
                .isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .consumedByNodeDryRunRequestEnvelopeProfile())
                .isEqualTo("managed-audit-manual-sandbox-connection-dry-run-request-envelope.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .envelopeFieldBoundary().operatorReviewFieldsComplete()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary().credentialHandleOnly()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary().credentialValueIncludedInEnvelope()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary().actualConnectionAttemptedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary().schemaMigrationSqlExecutedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary().approvalLedgerWrittenByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .readyForManagedAuditSandboxAdapterConnection()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt().receiptDigest())
                .startsWith("sha256:");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .readyForNodeV239ManualSandboxConnectionEvidenceVerification()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .receiptWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .consumedByNodeOperatorWindowChecklistProfile())
                .isEqualTo("managed-audit-manual-sandbox-connection-operator-window-checklist.v1");
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .checklistFieldBoundary().operatorChecklistReadOnly()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .approvalBoundary().allApprovalItemsRequired()).isTrue();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .credentialBoundary().credentialValueReadByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .javaExecutionBoundary().actualConnectionAttemptedByJava()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .readyForManagedAuditSandboxAdapterConnection()).isFalse();
        assertThat(headerBackedRehearsal.managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .receiptDigest()).startsWith("sha256:");
        assertThat(headerBackedRehearsal.failureTaxonomy().upstreamReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().authContextReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().authContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationPresent()).isTrue();
        assertThat(headerBackedRehearsal.failureTaxonomy().failureCategories())
                .containsExactly("READ_ONLY_EXECUTION_BLOCKED");
        assertThat(headerBackedRehearsal.failureTaxonomy().taxonomyWarnings())
                .containsExactly("REHEARSAL_REMAINS_READ_ONLY");
        assertThat(headerBackedRehearsal.verificationHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-verification-hint.v1");
        assertThat(headerBackedRehearsal.verificationHint().responseSchemaVersion())
                .isEqualTo("java-release-approval-rehearsal-response-schema.v47");
        assertThat(headerBackedRehearsal.verificationHint().warningDigest()).startsWith("sha256:");
        assertThat(headerBackedRehearsal.verificationHint().warningDigest())
                .isNotEqualTo(rehearsal.verificationHint().warningDigest());
        ReleaseApprovalRehearsalResponse repeatedHeaderBackedRehearsal =
                service.releaseApprovalRehearsal(headerBackedRehearsalRequest());
        assertThat(repeatedHeaderBackedRehearsal.verificationHint().warningDigest())
                .isEqualTo(headerBackedRehearsal.verificationHint().warningDigest());
        assertThat(repeatedHeaderBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardDigest())
                .isEqualTo(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardDigest());
        assertThat(repeatedHeaderBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardDigest())
                .isEqualTo(headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardDigest());
        assertThat(repeatedHeaderBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt().guardDigest())
                .isEqualTo(
                        headerBackedRehearsal.managedAuditSandboxAdapterApprovalSchemaGuardReceipt().guardDigest()
                );
        assertThat(repeatedHeaderBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerDigest())
                .isEqualTo(headerBackedRehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerDigest());
        assertThat(repeatedHeaderBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerDigest())
                .isEqualTo(headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerDigest());
        assertThat(headerBackedRehearsal.verificationHint().noLedgerWriteProved()).isTrue();
        assertThat(headerBackedRehearsal.verificationHint().nodeMayTreatAsProductionAuthorization()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().operatorAuthenticatedByJava()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().persistedByJava()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().approvalLedgerWritten()).isFalse();
        assertThat(headerBackedRehearsal.executionAllowed()).isFalse();
        assertThat(headerBackedRehearsal.executionBoundaries().nodeMayWriteApprovalLedger()).isFalse();
    }
}
