package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalResponse;
import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalTestSupport;
import org.junit.jupiter.api.Test;

class OpsEvidenceServiceReleaseApprovalRehearsalHeaderBackedOverviewTests
    extends ReleaseApprovalRehearsalTestSupport {

  @Test
  void buildsReleaseApprovalRehearsalOverviewForHeaderBackedRequest() {
    OpsEvidenceService service = readOnlyFixtureService();
    ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();

    ReleaseApprovalRehearsalResponse headerBackedRehearsal =
        service.releaseApprovalRehearsal(paddedHeaderBackedRehearsalRequest());
    assertThat(headerBackedRehearsal.requestContext().requestId()).isEqualTo("rehearsal-v67-001");
    assertThat(headerBackedRehearsal.requestContext().requestIdSource())
        .isEqualTo("X-Rehearsal-Request-Id");
    assertThat(headerBackedRehearsal.requestContext().operatorIdentity())
        .isEqualTo("release-operator@example.test");
    assertThat(headerBackedRehearsal.requestContext().operatorIdentitySource())
        .isEqualTo("X-Operator-Identity");
    assertThat(headerBackedRehearsal.requestContext().auditCorrelationId())
        .isEqualTo("audit-correlation-v67");
    assertThat(headerBackedRehearsal.requestContext().auditCorrelationSource())
        .isEqualTo("X-Audit-Correlation-Id");
    assertThat(headerBackedRehearsal.requestContext().contextWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorId()).isEqualTo("operator-198");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdSource())
        .isEqualTo("x-orderops-operator-id");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorRoles())
        .isEqualTo("operator,auditor");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesSource())
        .isEqualTo("x-orderops-roles");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaim())
        .isEqualTo("true");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimSource())
        .isEqualTo("x-orderops-operator-verified");
    assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationId())
        .isEqualTo("approval-v198-operator-window");
    assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationIdSource())
        .isEqualTo("x-orderops-approval-correlation-id");
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdentityEchoed()).isTrue();
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesEchoed()).isTrue();
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimEchoed()).isTrue();
    assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationEchoed()).isTrue();
    assertThat(headerBackedRehearsal.operatorWindowHint().operatorWindowContextComplete()).isTrue();
    assertThat(headerBackedRehearsal.operatorWindowHint().productionIdpVerifiedByJava()).isFalse();
    assertThat(headerBackedRehearsal.operatorWindowHint().persistedApprovalRecordByJava())
        .isFalse();
    assertThat(headerBackedRehearsal.operatorWindowHint().nodeMayTreatAsProductionIdentity())
        .isFalse();
    assertThat(headerBackedRehearsal.operatorWindowHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersion())
        .isEqualTo("real-read-window-ci-archive-artifact-manifest.v1");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionSource())
        .isEqualTo("x-orderops-ci-manifest-version");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigest())
        .isEqualTo("sha256:node-v200-manifest-digest");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestSource())
        .isEqualTo("x-orderops-ci-manifest-digest");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpoint())
        .isEqualTo("/api/v1/production/real-read-window-ci-archive-artifact-manifest");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointSource())
        .isEqualTo("x-orderops-ci-manifest-endpoint");
    assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCount()).isEqualTo("9");
    assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountSource())
        .isEqualTo("x-orderops-ci-artifact-record-count");
    assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationId())
        .isEqualTo("approval-v198-operator-window");
    assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationIdSource())
        .isEqualTo("x-orderops-ci-approval-correlation-id");
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionEchoed()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestEchoed()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointEchoed()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountEchoed()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationEchoed()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().ciEvidenceContextComplete()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().noLedgerWriteProved()).isTrue();
    assertThat(headerBackedRehearsal.ciEvidenceHint().ciArtifactUploadedByJava()).isFalse();
    assertThat(headerBackedRehearsal.ciEvidenceHint().githubArtifactAccessedByJava()).isFalse();
    assertThat(headerBackedRehearsal.ciEvidenceHint().productionWindowAllowedByJava()).isFalse();
    assertThat(headerBackedRehearsal.ciEvidenceHint().nodeMayTreatAsCiArtifactPublication())
        .isFalse();
    assertThat(headerBackedRehearsal.ciEvidenceHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersion())
        .isEqualTo("real-read-window-ci-artifact-upload-dry-run-contract.v1");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersionSource())
        .isEqualTo("x-orderops-ci-upload-contract-version");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigest())
        .isEqualTo("sha256:node-v202-upload-contract-digest");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigestSource())
        .isEqualTo("x-orderops-ci-upload-contract-digest");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactName())
        .isEqualTo("orderops-real-read-window-evidence-v191-v201");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactNameSource())
        .isEqualTo("x-orderops-ci-artifact-name");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRoot()).isEqualTo("c/");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRootSource())
        .isEqualTo("x-orderops-ci-artifact-root");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDays()).isEqualTo("30");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDaysSource())
        .isEqualTo("x-orderops-ci-retention-days");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadMode())
        .isEqualTo("dry-run-contract-only");
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadModeSource())
        .isEqualTo("x-orderops-ci-upload-mode");
    assertThat(headerBackedRehearsal.artifactRetentionHint().artifactRetentionContextComplete())
        .isTrue();
    assertThat(headerBackedRehearsal.artifactRetentionHint().retentionDaysWithinJavaRetention())
        .isTrue();
    assertThat(headerBackedRehearsal.artifactRetentionHint().javaRetentionFixtureReadOnly())
        .isTrue();
    assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactUploadedByJava()).isFalse();
    assertThat(headerBackedRehearsal.artifactRetentionHint().githubArtifactAccessedByJava())
        .isFalse();
    assertThat(headerBackedRehearsal.artifactRetentionHint().productionWindowAllowedByJava())
        .isFalse();
    assertThat(headerBackedRehearsal.artifactRetentionHint().nodeMayTreatAsRetentionAuthorization())
        .isFalse();
    assertThat(headerBackedRehearsal.artifactRetentionHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersion())
        .isEqualTo("three-project-real-read-runtime-smoke-preflight.v1");
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersionSource())
        .isEqualTo("x-orderops-runtime-preflight-version");
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigest())
        .isEqualTo("sha256:node-v204-preflight-digest");
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigestSource())
        .isEqualTo("x-orderops-runtime-preflight-digest");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionId())
        .isEqualTo("runtime-smoke-v205-session-001");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionIdSource())
        .isEqualTo("x-orderops-runtime-smoke-session-id");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetId())
        .isEqualTo("java-release-approval-rehearsal");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetIdSource())
        .isEqualTo("x-orderops-runtime-read-target-id");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowMode())
        .isEqualTo("manual-open-window-plan");
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowModeSource())
        .isEqualTo("x-orderops-runtime-window-mode");
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightVersionEchoed()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().sourcePreflightDigestEchoed()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeSessionIdEchoed()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeReadTargetIdEchoed()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeWindowModeEchoed()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().liveReadinessContextComplete()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().readyForRuntimeSmokeRead()).isTrue();
    assertThat(headerBackedRehearsal.liveReadinessHint().runtimeSmokeExecutedByJava()).isFalse();
    assertThat(headerBackedRehearsal.liveReadinessHint().javaStartedProcessForNode()).isFalse();
    assertThat(headerBackedRehearsal.liveReadinessHint().nodeMayTreatAsProductionAuthorization())
        .isFalse();
    assertThat(headerBackedRehearsal.liveReadinessHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateVersion())
        .isEqualTo("managed-audit-persistence-boundary-candidate.v1");
    assertThat(
            headerBackedRehearsal
                .auditPersistenceHandoffHint()
                .managedAuditCandidateVersionSource())
        .isEqualTo("x-orderops-managed-audit-candidate-version");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateDigest())
        .isEqualTo("sha256:node-v208-managed-audit-candidate-digest");
    assertThat(
            headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditCandidateDigestSource())
        .isEqualTo("x-orderops-managed-audit-candidate-digest");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditSinkMode())
        .isEqualTo("file-or-sqlite-dry-run-candidate");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditSinkModeSource())
        .isEqualTo("x-orderops-managed-audit-sink-mode");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRetentionDays())
        .isEqualTo("30");
    assertThat(
            headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRetentionDaysSource())
        .isEqualTo("x-orderops-managed-audit-retention-days");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRotationPolicy())
        .isEqualTo("size-and-age-rotation-candidate");
    assertThat(
            headerBackedRehearsal.auditPersistenceHandoffHint().managedAuditRotationPolicySource())
        .isEqualTo("x-orderops-managed-audit-rotation-policy");
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().candidateVersionEchoed())
        .isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().candidateDigestEchoed())
        .isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().sinkModeEchoed()).isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().retentionDaysEchoed()).isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().rotationPolicyEchoed()).isTrue();
    assertThat(
            headerBackedRehearsal
                .auditPersistenceHandoffHint()
                .auditPersistenceHandoffContextComplete())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .auditPersistenceHandoffHint()
                .managedAuditRetentionWithinJavaRetention())
        .isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaAuditSourceReadOnly())
        .isTrue();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaLedgerWriteAllowed())
        .isFalse();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().javaManagedAuditWriteAllowed())
        .isFalse();
    assertThat(
            headerBackedRehearsal.auditPersistenceHandoffHint().javaExternalAuditSystemAccessed())
        .isFalse();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().nodeMayUseAsManagedAuditInput())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .auditPersistenceHandoffHint()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(headerBackedRehearsal.auditPersistenceHandoffHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractVersion())
        .isEqualTo("managed-audit-identity-approval-binding-contract.v1");
    assertThat(
            headerBackedRehearsal
                .approvalRecordHandoffHint()
                .approvalBindingContractVersionSource())
        .isEqualTo("x-orderops-approval-binding-contract-version");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigest())
        .isEqualTo("sha256:node-v210-approval-binding-digest");
    assertThat(
            headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigestSource())
        .isEqualTo("x-orderops-approval-binding-contract-digest");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestId())
        .isEqualTo("approval-request-v210-001");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestIdSource())
        .isEqualTo("x-orderops-approval-request-id");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionState())
        .isEqualTo("APPROVED_DRY_RUN_ONLY");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionStateSource())
        .isEqualTo("x-orderops-approval-decision-state");
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationId())
        .isEqualTo("approval-record-correlation-v210");
    assertThat(
            headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationIdSource())
        .isEqualTo("x-orderops-approval-record-correlation-id");
    assertThat(
            headerBackedRehearsal
                .approvalRecordHandoffHint()
                .approvalBindingContractVersionEchoed())
        .isTrue();
    assertThat(
            headerBackedRehearsal.approvalRecordHandoffHint().approvalBindingContractDigestEchoed())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRequestIdEchoed())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalDecisionStateEchoed())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordCorrelationEchoed())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .approvalRecordHandoffHint()
                .approvalRecordHandoffContextComplete())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().approvalRecordFixtureReadOnly())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalDecisionCreated())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalLedgerWritten())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalRecordPersisted())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().javaApprovalRecordAuthenticated())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().productionApprovalStoreRequired())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().nodeMayUseAsAuditApprovalInput())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .approvalRecordHandoffHint()
                .nodeMayTreatAsProductionApprovalRecord())
        .isFalse();
    assertThat(headerBackedRehearsal.approvalRecordHandoffHint().echoWarnings()).isEmpty();
    assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().nodeV211HandoffAccepted())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .nodeV211NoWriteBoundaryAccepted())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .readyForNodeV213RestoreDrillPlan())
        .isTrue();
    assertThat(headerBackedRehearsal.approvalHandoffVerificationMarker().markerWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .nodeV211ProductionAuditRecordAllowed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .nodeV211RealApprovalDecisionCreated())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .nodeV211RealApprovalLedgerWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal.approvalHandoffVerificationMarker().javaApprovalRecordPersisted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .approvalHandoffVerificationMarker()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal.approvalHandoffVerificationMarker().consumedHandoffFieldPaths())
        .contains(
            "approvalRecordHandoffHint.approvalRecordCorrelationId",
            "approvalRecordHandoffHint.approvalTimestampPlaceholder",
            "verificationHint.warningDigest");
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .readyForNodeV215DryRunAdapterCandidate())
        .isTrue();
    assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().receiptWarnings())
        .isEmpty();
    assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayConsume())
        .isTrue();
  }
}
