package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalResponse;
import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalTestSupport;
import org.junit.jupiter.api.Test;

class OpsEvidenceServiceReleaseApprovalRehearsalSandboxConnectionOverviewTests
    extends ReleaseApprovalRehearsalTestSupport {

  @Test
  void buildsReleaseApprovalRehearsalSandboxConnectionOverviewForDefaultRequest() {
    OpsEvidenceService service = readOnlyFixtureService();

    ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();
    assertThat(rehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerVersion())
        .isEqualTo(
            "java-release-approval-rehearsal-managed-audit-sandbox-connection-operator-handoff-marker.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sourceSandboxAdapterApprovalSchemaGuardReceiptVersion())
        .isEqualTo(
            "java-release-approval-rehearsal-managed-audit-sandbox-adapter-approval-schema-guard-receipt.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sourceSandboxAdapterApprovalSchemaGuardSchemaVersion())
        .isEqualTo("java-release-approval-rehearsal-response-schema.v16");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeEvidenceChecklistVersion())
        .isEqualTo("Node v227");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeEvidenceChecklistProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-evidence-checklist.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketVersion())
        .isEqualTo("Node v228");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-operator-packet.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketEndpoint())
        .isEqualTo("/api/v1/audit/managed-audit-manual-sandbox-connection-operator-packet");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketState())
        .isEqualTo("manual-sandbox-connection-operator-packet-ready");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .nextNodePacketVerificationVersion())
        .isEqualTo("Node v229");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .nextNodePacketVerificationProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-packet-verification.v1");
    assertThat(rehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().nodeV229MayConsume())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .manualSandboxConnectionWindowRequired())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .manualSandboxConnectionWindowOpenedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .javaStartsManagedAuditService())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .nodeAutoStartAllowed())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .ownerApprovalArtifactIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .schemaRehearsalIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .operatorPacketReadOnly())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .ownerApprovalArtifactIdFieldRecognizedByJava())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .schemaRehearsalIdFieldRecognizedByJava())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .packetCreatesApprovalDecision())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialHandleNameField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialHandleNameRecognizedByJava())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialValueRequiredByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary()
                .rollbackPathIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary()
                .manualAbortMarkerField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary()
                .timeoutBudgetMs())
        .isEqualTo(15000);
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary()
                .rollbackExecutionAllowedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary()
                .approvalLedgerWrittenByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary()
                .externalManagedAuditConnectionOpenedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary()
                .sqlExecutedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForNodeV229ManualSandboxConnectionPacketVerification())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForProductionAudit())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(rehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerDigest())
        .startsWith("sha256:");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .acceptedOperatorPacketFields())
        .contains(
            "ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID",
            "ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE",
            "ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID",
            "ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID",
            "ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .forbiddenHandoffOperations())
        .contains(
            "Open a managed audit sandbox connection during Java v87 marker",
            "Execute schema migration SQL during Java v87 marker",
            "Write approval ledger or managed audit state during Java v87 marker");
    assertThat(
            rehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().nodeV229Prerequisites())
        .contains(
            "Node v228 manual sandbox connection operator packet must be archived",
            "Java v87 sandbox connection operator handoff marker must be ready",
            "mini-kv v96 sandbox connection receipt echo marker must be ready");
    assertThat(rehearsal.managedAuditSandboxConnectionOperatorHandoffMarker().markerWarnings())
        .containsExactly(
            "NODE_V229_SOURCE_SANDBOX_ADAPTER_APPROVAL_SCHEMA_GUARD_RECEIPT_NOT_READY");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .nodeVerificationActions())
        .contains(
            "Compare managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeOperatorPacketProfile with Node v228",
            "Require managedAuditSandboxConnectionOperatorHandoffMarker.readyForNodeV229ManualSandboxConnectionPacketVerification=true before Node v229",
            "Keep managedAuditSandboxConnectionOperatorHandoffMarker.credentialBoundary.credentialValueReadByJava=false",
            "Keep managedAuditSandboxConnectionOperatorHandoffMarker.sandboxConnectionWindowBoundary.manualSandboxConnectionWindowOpenedByJava=false");
    assertThat(rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerVersion())
        .isEqualTo(
            "java-release-approval-rehearsal-managed-audit-sandbox-connection-preflight-echo-marker.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sourceSandboxConnectionOperatorHandoffMarkerVersion())
        .isEqualTo(
            "java-release-approval-rehearsal-managed-audit-sandbox-connection-operator-handoff-marker.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sourceSandboxConnectionOperatorHandoffSchemaVersion())
        .isEqualTo("java-release-approval-rehearsal-response-schema.v17");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateVersion())
        .isEqualTo("Node v230");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-preflight-gate.v1");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateEndpoint())
        .isEqualTo("/api/v1/audit/managed-audit-manual-sandbox-connection-preflight-gate");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateState())
        .isEqualTo("manual-sandbox-connection-preflight-gate-ready");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .nextNodePreflightVerificationVersion())
        .isEqualTo("Node v231");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .nextNodePreflightVerificationProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-preflight-verification.v1");
    assertThat(rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().nodeV231MayConsume())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowFlagName())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowFlagRequired())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowOpenByDefault())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowOpenedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .nodeAutoStartAllowed())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .ownerApprovalArtifactIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .schemaRehearsalIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .rollbackPathIdField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .timeoutBudgetMs())
        .isEqualTo(15000);
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .manualAbortMarkerField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .allRequiredPreflightFieldsRecognizedByJava())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .preflightGateReadOnly())
        .isTrue();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .gateCreatesConnectionCommand())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .credentialBoundary()
                .credentialHandleNameField())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .rollbackPathBoundary()
                .rollbackExecutionAllowedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary()
                .externalManagedAuditConnectionOpenedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary()
                .approvalLedgerWrittenByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary()
                .sqlExecutedByJava())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForNodeV231ManualSandboxConnectionPreflightVerification())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().readyForProductionAudit())
        .isFalse();
    assertThat(
            rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().readyForProductionWindow())
        .isFalse();
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerDigest())
        .startsWith("sha256:");
    assertThat(
            rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().requiredPreflightFields())
        .containsExactly(
            "ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID",
            "ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE",
            "ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID",
            "ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID",
            "timeoutBudgetMs=15000",
            "ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT",
            "ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED");
    assertThat(
            rehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .forbiddenPreflightOperations())
        .contains(
            "Open a managed audit sandbox connection during Java v88 preflight echo",
            "Execute schema migration SQL during Java v88 preflight echo",
            "Start Java, mini-kv, or external audit services automatically");
    assertThat(rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().nodeV231Prerequisites())
        .contains(
            "Node v230 manual sandbox connection preflight gate must be archived",
            "Java v88 sandbox connection preflight echo marker must be ready",
            "mini-kv v97 no-start guard receipt must be ready");
    assertThat(rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerWarnings())
        .containsExactly("NODE_V231_SOURCE_SANDBOX_CONNECTION_OPERATOR_HANDOFF_MARKER_NOT_READY");
    assertThat(
            rehearsal.managedAuditSandboxConnectionPreflightEchoMarker().nodeVerificationActions())
        .contains(
            "Compare managedAuditSandboxConnectionPreflightEchoMarker.consumedByNodePreflightGateProfile with Node v230",
            "Require managedAuditSandboxConnectionPreflightEchoMarker.readyForNodeV231ManualSandboxConnectionPreflightVerification=true before Node v231",
            "Compare managedAuditSandboxConnectionPreflightEchoMarker.requiredPreflightFields with Node v230 preflightFields",
            "Keep managedAuditSandboxConnectionPreflightEchoMarker.credentialBoundary.credentialValueReadByJava=false");
  }
}
