package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

import com.codexdemo.orderplatform.notification.FailedEventSummaryResponse;
import com.codexdemo.orderplatform.notification.FailedEventSummaryService;
import com.codexdemo.orderplatform.order.IdempotencyStore;
import com.codexdemo.orderplatform.order.IdempotencyStoreDescriptor;
import com.codexdemo.orderplatform.outbox.OutboxPublisherProperties;
import com.codexdemo.orderplatform.outbox.OutboxRabbitMqProperties;
import com.codexdemo.orderplatform.outbox.OutboxRepository;
import java.time.Instant;
import org.junit.jupiter.api.Test;
import org.springframework.mock.env.MockEnvironment;

class OpsEvidenceServiceTests {

    private final FailedEventSummaryService failedEventSummaryService =
            org.mockito.Mockito.mock(FailedEventSummaryService.class);

    private final OutboxRepository outboxRepository = org.mockito.Mockito.mock(OutboxRepository.class);

    private final IdempotencyStore idempotencyStore = org.mockito.Mockito.mock(IdempotencyStore.class);

    @Test
    void buildsReadOnlyEvidenceForControlPlane() {
        Instant latestFailedAt = Instant.parse("2026-05-12T01:00:00Z");
        Instant latestApprovalAt = Instant.parse("2026-05-12T01:05:00Z");
        when(failedEventSummaryService.summary()).thenReturn(new FailedEventSummaryResponse(
                Instant.parse("2026-05-12T01:10:00Z"),
                4,
                2,
                1,
                1,
                latestFailedAt,
                latestApprovalAt,
                3
        ));
        when(outboxRepository.countByPublishedAtIsNull()).thenReturn(6L);
        when(idempotencyStore.descriptor()).thenReturn(new IdempotencyStoreDescriptor(
                "java-idempotency-store.v1",
                "jpa-order-idempotency-store",
                "JpaIdempotencyStore",
                "JPA_DATABASE",
                "orders table",
                "orders.idempotency_key",
                "orders.idempotency_request_fingerprint",
                true,
                false,
                false,
                true,
                false,
                "DISABLED_CANDIDATE_ONLY",
                "mini-kv-ttl-token-adapter is documented for later TTL-token experiments, not wired into create-order.",
                false
        ));

        OutboxPublisherProperties outboxPublisherProperties = new OutboxPublisherProperties();
        outboxPublisherProperties.setEnabled(false);
        OutboxRabbitMqProperties outboxRabbitMqProperties = new OutboxRabbitMqProperties();
        outboxRabbitMqProperties.setEnabled(false);
        outboxRabbitMqProperties.setExchange("order-platform.outbox");
        outboxRabbitMqProperties.setQueue("order-platform.outbox.events");
        outboxRabbitMqProperties.setDeadLetterQueue("order-platform.outbox.events.dlq");
        MockEnvironment environment = new MockEnvironment()
                .withProperty("spring.application.name", "advanced-order-platform")
                .withProperty("info.app.version", "0.1.0-test");
        environment.setActiveProfiles("local", "ops");

        OpsEvidenceService service = new OpsEvidenceService(
                failedEventSummaryService,
                outboxRepository,
                outboxPublisherProperties,
                outboxRabbitMqProperties,
                idempotencyStore,
                environment
        );

        OpsEvidenceResponse evidence = service.evidence();

        assertThat(evidence.evidenceVersion()).isEqualTo("java-ops-evidence.v1");
        assertThat(evidence.readOnly()).isTrue();
        assertThat(evidence.executionAllowed()).isFalse();
        assertThat(evidence.service().name()).isEqualTo("advanced-order-platform");
        assertThat(evidence.service().version()).isEqualTo("0.1.0-test");
        assertThat(evidence.service().profiles()).containsExactly("local", "ops");
        assertThat(evidence.healthProbe().endpoint()).isEqualTo("/actuator/health");
        assertThat(evidence.healthProbe().method()).isEqualTo("GET");
        assertThat(evidence.healthProbe().expectedStatus()).isEqualTo("UP");
        assertThat(evidence.healthProbe().evidenceEndpoint()).isEqualTo("/api/v1/ops/evidence");
        assertThat(evidence.healthProbe().additionalProbeEndpoints())
                .containsExactly(
                        "/api/v1/ops/overview",
                        "/api/v1/ops/release-approval-rehearsal",
                        "/contracts/ops-read-only-evidence.sample.json",
                        "/contracts/order-idempotency-boundary.sample.json",
                        "/contracts/order-idempotency-store-abstraction.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json"
                );
        assertThat(evidence.healthProbe().liveProbeRequiredForPass()).isTrue();
        assertThat(evidence.healthProbe().staticSampleOnly()).isFalse();
        assertThat(evidence.readOnlyWindow().windowVersion()).isEqualTo("java-read-only-window.v1");
        assertThat(evidence.readOnlyWindow().operatorStartRequired()).isTrue();
        assertThat(evidence.readOnlyWindow().nodeAutoStartAllowed()).isFalse();
        assertThat(evidence.readOnlyWindow().upstreamProbesRequired()).isTrue();
        assertThat(evidence.readOnlyWindow().upstreamActionsAllowed()).isFalse();
        assertThat(evidence.readOnlyWindow().readyForReadOnlyLiveProbe()).isTrue();
        assertThat(evidence.readOnlyWindow().readyForProductionOperations()).isFalse();
        assertThat(evidence.readOnlyWindow().allowedProbeEndpoints())
                .containsExactly(
                        "GET /actuator/health",
                        "GET /api/v1/ops/overview",
                        "GET /api/v1/ops/evidence",
                        "GET /api/v1/ops/release-approval-rehearsal",
                        "GET /contracts/ops-read-only-evidence.sample.json",
                        "GET /contracts/order-idempotency-boundary.sample.json",
                        "GET /contracts/order-idempotency-store-abstraction.sample.json",
                        "GET /contracts/release-verification-manifest.sample.json",
                        "GET /contracts/deployment-rollback-evidence.sample.json",
                        "GET /contracts/release-bundle-manifest.sample.json",
                        "GET /contracts/release-handoff-checklist.fixture.json",
                        "GET /contracts/release-audit-retention.fixture.json",
                        "GET /contracts/release-operator-signoff.fixture.json",
                        "GET /contracts/rollback-approver-evidence.fixture.json",
                        "GET /contracts/rollback-approval-handoff.sample.json",
                        "GET /contracts/rollback-approval-record.fixture.json",
                        "GET /contracts/rollback-sql-review-gate.sample.json",
                        "GET /contracts/production-secret-source-contract.sample.json",
                        "GET /contracts/production-deployment-runbook-contract.sample.json"
                );
        assertThat(evidence.readOnlyWindow().forbiddenOperations())
                .contains(
                        "POST /api/v1/failed-events/{id}/replay",
                        "Any non-GET Node upstream action"
                );
        assertThat(evidence.readOnlyWindow().requiredNodeEnvironment())
                .containsExactly("UPSTREAM_PROBES_ENABLED=true", "UPSTREAM_ACTIONS_ENABLED=false");
        assertThat(evidence.readOnlyWindow().replayPostBoundary())
                .contains("must not call POST /api/v1/failed-events/{id}/replay");
        assertThat(evidence.orderIdempotency().boundaryVersion()).isEqualTo("java-order-idempotency-boundary.v1");
        assertThat(evidence.orderIdempotency().storeAbstractionVersion()).isEqualTo("java-idempotency-store.v1");
        assertThat(evidence.orderIdempotency().createOrderEndpoint()).isEqualTo("/api/v1/orders");
        assertThat(evidence.orderIdempotency().requiredHeader()).isEqualTo("Idempotency-Key");
        assertThat(evidence.orderIdempotency().requestFingerprintVersion())
                .isEqualTo("order-create-request-sha256.v1");
        assertThat(evidence.orderIdempotency().sameKeyDifferentRequestErrorCode())
                .isEqualTo("IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST");
        assertThat(evidence.orderIdempotency().activeStore()).isEqualTo("jpa-order-idempotency-store");
        assertThat(evidence.orderIdempotency().activeStoreImplementation()).isEqualTo("JpaIdempotencyStore");
        assertThat(evidence.orderIdempotency().activeStoreMode()).isEqualTo("JPA_DATABASE");
        assertThat(evidence.orderIdempotency().authoritativeStore())
                .isEqualTo("orders table via orders.idempotency_key and orders.idempotency_request_fingerprint");
        assertThat(evidence.orderIdempotency().storeCandidates())
                .extracting(OpsEvidenceResponse.IdempotencyStoreCandidate::name)
                .containsExactly("jpa-order-idempotency-store", "mini-kv-ttl-token-adapter");
        assertThat(evidence.orderIdempotency().storeCandidates().get(1).enabled()).isFalse();
        assertThat(evidence.orderIdempotency().storeCandidates().get(1).connected()).isFalse();
        assertThat(evidence.orderIdempotency().storeCandidates().get(1).mode())
                .isEqualTo("DISABLED_CANDIDATE_ONLY");
        assertThat(evidence.orderIdempotency().miniKvConnected()).isFalse();
        assertThat(evidence.orderIdempotency().externalTokenStoreConnected()).isFalse();
        assertThat(evidence.orderIdempotency().changesPaymentOrInventoryTransaction()).isFalse();
        assertThat(evidence.releaseVerification().manifestVersion())
                .isEqualTo("java-release-verification-manifest.v1");
        assertThat(evidence.releaseVerification().manifestEndpoint())
                .isEqualTo("/contracts/release-verification-manifest.sample.json");
        assertThat(evidence.releaseVerification().verificationMode())
                .isEqualTo("LOCAL_OPERATOR_EXECUTES_AND_ARCHIVES_RESULTS");
        assertThat(evidence.releaseVerification().requiredChecks())
                .containsExactly(
                        "focused-maven-tests",
                        "non-docker-regression-tests",
                        "maven-package",
                        "http-smoke",
                        "static-contract-json-validation"
                );
        assertThat(evidence.releaseVerification().staticContractEndpoints())
                .contains(
                        "/contracts/order-idempotency-store-abstraction.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/release-bundle-manifest.sample.json"
                );
        assertThat(evidence.releaseVerification().nodeMayExecuteBuild()).isFalse();
        assertThat(evidence.releaseVerification().nodeMayTriggerWrites()).isFalse();
        assertThat(evidence.releaseVerification().changesBusinessSemantics()).isFalse();
        assertThat(evidence.releaseVerification().requiresProductionSecrets()).isFalse();
        assertThat(evidence.deploymentRollback().evidenceVersion())
                .isEqualTo("java-deployment-rollback-evidence.v1");
        assertThat(evidence.deploymentRollback().evidenceEndpoint())
                .isEqualTo("/contracts/deployment-rollback-evidence.sample.json");
        assertThat(evidence.deploymentRollback().rollbackMode()).isEqualTo("READ_ONLY_BOUNDARY_SAMPLE");
        assertThat(evidence.deploymentRollback().rollbackSubjects())
                .containsExactly(
                        "java-package",
                        "runtime-configuration",
                        "database-migrations",
                        "static-contracts"
                );
        assertThat(evidence.deploymentRollback().requiresOperatorConfirmation())
                .containsExactly(
                        "artifact-version-target",
                        "deployment-window-owner",
                        "rollback-approver",
                        "configuration-secret-source",
                        "production-secret-source-contract",
                        "production-deployment-runbook-contract",
                        "database-migration-direction",
                        "release-handoff-checklist-fixture",
                        "release-audit-retention-fixture",
                        "release-operator-signoff-fixture",
                        "rollback-approver-evidence-fixture",
                        "rollback-approval-handoff",
                        "rollback-approval-record-fixture",
                        "rollback-sql-review-gate"
                );
        assertThat(evidence.deploymentRollback().packageRollbackSupported()).isTrue();
        assertThat(evidence.deploymentRollback().configRollbackSupported()).isTrue();
        assertThat(evidence.deploymentRollback().databaseMigrationRollbackAutomatic()).isFalse();
        assertThat(evidence.deploymentRollback().contractsRollbackByArtifactVersion()).isTrue();
        assertThat(evidence.deploymentRollback().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.deploymentRollback().requiresProductionDatabase()).isFalse();
        assertThat(evidence.deploymentRollback().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.releaseBundle().manifestVersion())
                .isEqualTo("java-release-bundle-manifest.v1");
        assertThat(evidence.releaseBundle().manifestEndpoint())
                .isEqualTo("/contracts/release-bundle-manifest.sample.json");
        assertThat(evidence.releaseBundle().bundleMode()).isEqualTo("READ_ONLY_RELEASE_BUNDLE");
        assertThat(evidence.releaseBundle().artifact())
                .isEqualTo("target/advanced-order-platform-0.1.0-SNAPSHOT.jar");
        assertThat(evidence.releaseBundle().contractEndpoints())
                .containsExactly(
                        "/contracts/ops-read-only-evidence.sample.json",
                        "/contracts/ops-evidence-field-guide.sample.json",
                        "/contracts/order-idempotency-boundary.sample.json",
                        "/contracts/order-idempotency-store-abstraction.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json"
                );
        assertThat(evidence.releaseBundle().requiredEvidence())
                .containsExactly(
                        "focused-maven-tests",
                        "non-docker-regression-tests",
                        "maven-package",
                        "http-smoke",
                        "static-contract-json-validation"
                );
        assertThat(evidence.releaseBundle().nodeMayConsume()).isTrue();
        assertThat(evidence.releaseBundle().nodeMayExecuteBuild()).isFalse();
        assertThat(evidence.releaseBundle().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.releaseBundle().requiresProductionDatabase()).isFalse();
        assertThat(evidence.releaseBundle().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().fixtureVersion())
                .isEqualTo("java-release-handoff-checklist-fixture.v1");
        assertThat(evidence.releaseHandoffChecklistFixture().fixtureEndpoint())
                .isEqualTo("/contracts/release-handoff-checklist.fixture.json");
        assertThat(evidence.releaseHandoffChecklistFixture().fixtureMode())
                .isEqualTo("READ_ONLY_RELEASE_HANDOFF_CHECKLIST_FIXTURE");
        assertThat(evidence.releaseHandoffChecklistFixture().releaseOperator())
                .isEqualTo("release-operator-placeholder");
        assertThat(evidence.releaseHandoffChecklistFixture().rollbackApprover())
                .isEqualTo("rollback-approver-placeholder");
        assertThat(evidence.releaseHandoffChecklistFixture().artifactTarget())
                .isEqualTo("release-tag-or-artifact-version-placeholder");
        assertThat(evidence.releaseHandoffChecklistFixture().migrationDirectionOptions())
                .containsExactly(
                        "forward-only",
                        "rollback-script-reviewed",
                        "no-database-change"
                );
        assertThat(evidence.releaseHandoffChecklistFixture().selectedMigrationDirection())
                .isEqualTo("no-database-change");
        assertThat(evidence.releaseHandoffChecklistFixture().secretSourceConfirmation())
                .isEqualTo("/contracts/production-secret-source-contract.sample.json");
        assertThat(evidence.releaseHandoffChecklistFixture().requiredChecklistFields())
                .containsExactly(
                        "release-operator",
                        "rollback-approver",
                        "artifact-target",
                        "database-migration-direction",
                        "secret-source-confirmation",
                        "deployment-runbook-contract",
                        "rollback-approval-record-fixture",
                        "release-audit-retention-fixture",
                        "release-operator-signoff-fixture",
                        "rollback-approver-evidence-fixture",
                        "no-secret-value-boundary"
                );
        assertThat(evidence.releaseHandoffChecklistFixture().checklistArtifacts())
                .containsExactly(
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json"
                );
        assertThat(evidence.releaseHandoffChecklistFixture().noSecretValueBoundaries())
                .containsExactly(
                        "checklist-fixture-stores-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-handoff-checklist",
                        "node-may-render-release-handoff-review-only"
                );
        assertThat(evidence.releaseHandoffChecklistFixture().nodeMayConsume()).isTrue();
        assertThat(evidence.releaseHandoffChecklistFixture().nodeMayTriggerDeployment()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().deploymentExecutionAllowed()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().requiresProductionDatabase()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().requiresProductionSecrets()).isFalse();
        assertThat(evidence.releaseHandoffChecklistFixture().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().fixtureVersion())
                .isEqualTo("java-release-audit-retention-fixture.v1");
        assertThat(evidence.releaseAuditRetentionFixture().fixtureEndpoint())
                .isEqualTo("/contracts/release-audit-retention.fixture.json");
        assertThat(evidence.releaseAuditRetentionFixture().fixtureMode())
                .isEqualTo("READ_ONLY_RELEASE_AUDIT_RETENTION_FIXTURE");
        assertThat(evidence.releaseAuditRetentionFixture().retentionId())
                .isEqualTo("release-retention-record-placeholder");
        assertThat(evidence.releaseAuditRetentionFixture().releaseOperator())
                .isEqualTo("release-operator-placeholder");
        assertThat(evidence.releaseAuditRetentionFixture().artifactTarget())
                .isEqualTo("release-tag-or-artifact-version-placeholder");
        assertThat(evidence.releaseAuditRetentionFixture().retentionDays()).isEqualTo(180);
        assertThat(evidence.releaseAuditRetentionFixture().evidenceEndpoints())
                .containsExactly(
                        "/api/v1/ops/evidence",
                        "/api/v1/ops/release-approval-rehearsal",
                        "/api/v1/failed-events/replay-evidence-index",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/production-deployment-runbook-contract.sample.json"
                );
        assertThat(evidence.releaseAuditRetentionFixture().auditExportFields())
                .containsExactly(
                        "retention-id",
                        "release-operator",
                        "artifact-target",
                        "retention-days",
                        "evidence-endpoints",
                        "release-operator-signoff-fixture",
                        "rollback-approver-evidence-fixture",
                        "audit-export-location-placeholder",
                        "no-secret-value-boundary"
                );
        assertThat(evidence.releaseAuditRetentionFixture().retainedArtifacts())
                .containsExactly(
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/production-secret-source-contract.sample.json"
                );
        assertThat(evidence.releaseAuditRetentionFixture().noSecretValueBoundaries())
                .containsExactly(
                        "retention-fixture-stores-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-retention-record",
                        "node-may-render-retention-gate-only"
                );
        assertThat(evidence.releaseAuditRetentionFixture().nodeMayConsume()).isTrue();
        assertThat(evidence.releaseAuditRetentionFixture().nodeMayTriggerDeployment()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().auditExportReadOnly()).isTrue();
        assertThat(evidence.releaseAuditRetentionFixture().deploymentExecutionAllowed()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().requiresProductionDatabase()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().requiresProductionSecrets()).isFalse();
        assertThat(evidence.releaseAuditRetentionFixture().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().fixtureVersion())
                .isEqualTo("java-release-operator-signoff-fixture.v1");
        assertThat(evidence.releaseOperatorSignoffFixture().fixtureEndpoint())
                .isEqualTo("/contracts/release-operator-signoff.fixture.json");
        assertThat(evidence.releaseOperatorSignoffFixture().fixtureMode())
                .isEqualTo("READ_ONLY_RELEASE_OPERATOR_SIGNOFF_FIXTURE");
        assertThat(evidence.releaseOperatorSignoffFixture().releaseOperator())
                .isEqualTo("release-operator-placeholder");
        assertThat(evidence.releaseOperatorSignoffFixture().rollbackApprover())
                .isEqualTo("rollback-approver-placeholder");
        assertThat(evidence.releaseOperatorSignoffFixture().releaseWindow())
                .isEqualTo("release-window-placeholder");
        assertThat(evidence.releaseOperatorSignoffFixture().artifactTarget())
                .isEqualTo("release-tag-or-artifact-version-placeholder");
        assertThat(evidence.releaseOperatorSignoffFixture().operatorSignoffPlaceholder())
                .isEqualTo("operator-signoff-placeholder");
        assertThat(evidence.releaseOperatorSignoffFixture().requiredSignoffFields())
                .containsExactly(
                        "release-operator",
                        "rollback-approver",
                        "release-window",
                        "artifact-target",
                        "operator-signoff-placeholder",
                        "release-audit-retention-fixture",
                        "rollback-approver-evidence-fixture",
                        "no-secret-value-boundary"
                );
        assertThat(evidence.releaseOperatorSignoffFixture().signoffArtifacts())
                .containsExactly(
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-handoff.sample.json"
                );
        assertThat(evidence.releaseOperatorSignoffFixture().noSecretValueBoundaries())
                .containsExactly(
                        "signoff-fixture-stores-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-signoff",
                        "node-may-render-approval-prerequisite-gate-only"
                );
        assertThat(evidence.releaseOperatorSignoffFixture().nodeMayConsume()).isTrue();
        assertThat(evidence.releaseOperatorSignoffFixture().nodeMayCreateApprovalDecision()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().nodeMayTriggerDeployment()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().deploymentExecutionAllowed()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().requiresProductionDatabase()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().requiresProductionSecrets()).isFalse();
        assertThat(evidence.releaseOperatorSignoffFixture().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().fixtureVersion())
                .isEqualTo("java-rollback-approver-evidence-fixture.v1");
        assertThat(evidence.rollbackApproverEvidenceFixture().fixtureEndpoint())
                .isEqualTo("/contracts/rollback-approver-evidence.fixture.json");
        assertThat(evidence.rollbackApproverEvidenceFixture().fixtureMode())
                .isEqualTo("READ_ONLY_ROLLBACK_APPROVER_EVIDENCE_FIXTURE");
        assertThat(evidence.rollbackApproverEvidenceFixture().rollbackApprover())
                .isEqualTo("rollback-approver-placeholder");
        assertThat(evidence.rollbackApproverEvidenceFixture().migrationDirectionOptions())
                .containsExactly(
                        "forward-only",
                        "rollback-script-reviewed",
                        "no-database-change"
                );
        assertThat(evidence.rollbackApproverEvidenceFixture().selectedMigrationDirection())
                .isEqualTo("no-database-change");
        assertThat(evidence.rollbackApproverEvidenceFixture().rollbackSqlArtifactReference())
                .isEqualTo("rollback-sql-artifact-reference-placeholder");
        assertThat(evidence.rollbackApproverEvidenceFixture().productionDatabaseBoundary())
                .isEqualTo("production-database-connection-outside-this-fixture");
        assertThat(evidence.rollbackApproverEvidenceFixture().requiredEvidenceFields())
                .containsExactly(
                        "rollback-approver",
                        "database-migration-direction",
                        "rollback-sql-artifact-reference",
                        "production-database-access-boundary",
                        "rollback-sql-review-gate",
                        "no-secret-value-boundary"
                );
        assertThat(evidence.rollbackApproverEvidenceFixture().evidenceArtifacts())
                .containsExactly(
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/release-bundle-manifest.sample.json"
                );
        assertThat(evidence.rollbackApproverEvidenceFixture().noSecretValueBoundaries())
                .containsExactly(
                        "rollback-approver-fixture-stores-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-approver-evidence",
                        "node-may-render-decision-rehearsal-input-only"
                );
        assertThat(evidence.rollbackApproverEvidenceFixture().nodeMayConsume()).isTrue();
        assertThat(evidence.rollbackApproverEvidenceFixture().nodeMayCreateApprovalDecision()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().rollbackExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().requiresProductionDatabase()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().requiresProductionSecrets()).isFalse();
        assertThat(evidence.rollbackApproverEvidenceFixture().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.rollbackApprovalHandoff().handoffVersion())
                .isEqualTo("java-rollback-approval-handoff.v1");
        assertThat(evidence.rollbackApprovalHandoff().handoffEndpoint())
                .isEqualTo("/contracts/rollback-approval-handoff.sample.json");
        assertThat(evidence.rollbackApprovalHandoff().approvalMode())
                .isEqualTo("OPERATOR_CONFIRMATION_REQUIRED");
        assertThat(evidence.rollbackApprovalHandoff().requiredConfirmationFields())
                .containsExactly(
                        "artifact-version-target",
                        "deployment-window-owner",
                        "rollback-approver",
                        "runtime-config-profile",
                        "configuration-secret-source",
                        "production-secret-source-contract",
                        "production-deployment-runbook-contract",
                        "database-migration-direction",
                        "release-handoff-checklist-fixture",
                        "release-audit-retention-fixture",
                        "release-operator-signoff-fixture",
                        "rollback-approver-evidence-fixture",
                        "rollback-approval-record-fixture",
                        "rollback-sql-review-gate",
                        "release-bundle-manifest",
                        "deployment-rollback-evidence"
                );
        assertThat(evidence.rollbackApprovalHandoff().handoffArtifacts())
                .containsExactly(
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/release-verification-manifest.sample.json"
                );
        assertThat(evidence.rollbackApprovalHandoff().nodeMayConsume()).isTrue();
        assertThat(evidence.rollbackApprovalHandoff().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.rollbackApprovalHandoff().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackApprovalHandoff().requiresProductionDatabase()).isFalse();
        assertThat(evidence.rollbackApprovalHandoff().requiresProductionSecrets()).isFalse();
        assertThat(evidence.rollbackApprovalHandoff().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().fixtureVersion())
                .isEqualTo("java-rollback-approval-record-fixture.v1");
        assertThat(evidence.rollbackApprovalRecordFixture().fixtureEndpoint())
                .isEqualTo("/contracts/rollback-approval-record.fixture.json");
        assertThat(evidence.rollbackApprovalRecordFixture().fixtureMode())
                .isEqualTo("READ_ONLY_APPROVAL_RECORD_FIXTURE");
        assertThat(evidence.rollbackApprovalRecordFixture().reviewer())
                .isEqualTo("rollback-reviewer-placeholder");
        assertThat(evidence.rollbackApprovalRecordFixture().approvalTimestampPlaceholder())
                .isEqualTo("approval-timestamp-placeholder");
        assertThat(evidence.rollbackApprovalRecordFixture().rollbackTarget())
                .isEqualTo("release-tag-or-artifact-version-placeholder");
        assertThat(evidence.rollbackApprovalRecordFixture().migrationDirectionOptions())
                .containsExactly(
                        "forward-only",
                        "rollback-script-reviewed",
                        "no-database-change"
                );
        assertThat(evidence.rollbackApprovalRecordFixture().selectedMigrationDirection())
                .isEqualTo("no-database-change");
        assertThat(evidence.rollbackApprovalRecordFixture().requiredRecordFields())
                .containsExactly(
                        "reviewer",
                        "approval-timestamp-placeholder",
                        "rollback-target",
                        "database-migration-direction",
                        "rollback-sql-review-gate",
                        "no-secret-value-boundary"
                );
        assertThat(evidence.rollbackApprovalRecordFixture().recordArtifacts())
                .containsExactly(
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/release-bundle-manifest.sample.json"
                );
        assertThat(evidence.rollbackApprovalRecordFixture().noSecretValueBoundaries())
                .containsExactly(
                        "record-fixture-stores-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-approval-record",
                        "node-may-render-release-window-packet-only"
                );
        assertThat(evidence.rollbackApprovalRecordFixture().nodeMayConsume()).isTrue();
        assertThat(evidence.rollbackApprovalRecordFixture().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().rollbackExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().rollbackSqlExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().requiresProductionDatabase()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().requiresProductionSecrets()).isFalse();
        assertThat(evidence.rollbackApprovalRecordFixture().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.rollbackSqlReviewGate().gateVersion())
                .isEqualTo("java-rollback-sql-review-gate.v1");
        assertThat(evidence.rollbackSqlReviewGate().gateEndpoint())
                .isEqualTo("/contracts/rollback-sql-review-gate.sample.json");
        assertThat(evidence.rollbackSqlReviewGate().gateMode())
                .isEqualTo("READ_ONLY_SQL_REVIEW_GATE");
        assertThat(evidence.rollbackSqlReviewGate().reviewOwner()).isEqualTo("database-release-owner");
        assertThat(evidence.rollbackSqlReviewGate().requiredReviewFields())
                .containsExactly(
                        "rollback-sql-review-owner",
                        "migration-direction",
                        "operator-approval-placeholder",
                        "rollback-sql-artifact-reference",
                        "production-database-access-boundary"
                );
        assertThat(evidence.rollbackSqlReviewGate().migrationDirectionOptions())
                .containsExactly(
                        "forward-only",
                        "rollback-script-reviewed",
                        "no-database-change"
                );
        assertThat(evidence.rollbackSqlReviewGate().operatorApprovalPlaceholder())
                .isEqualTo("operator-approval-required-before-any-sql-execution");
        assertThat(evidence.rollbackSqlReviewGate().nodeMayConsume()).isTrue();
        assertThat(evidence.rollbackSqlReviewGate().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.rollbackSqlReviewGate().sqlExecutionAllowed()).isFalse();
        assertThat(evidence.rollbackSqlReviewGate().requiresProductionDatabase()).isFalse();
        assertThat(evidence.rollbackSqlReviewGate().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.productionSecretSourceContract().contractVersion())
                .isEqualTo("java-production-secret-source-contract.v1");
        assertThat(evidence.productionSecretSourceContract().contractEndpoint())
                .isEqualTo("/contracts/production-secret-source-contract.sample.json");
        assertThat(evidence.productionSecretSourceContract().contractMode())
                .isEqualTo("READ_ONLY_SECRET_SOURCE_CONTRACT");
        assertThat(evidence.productionSecretSourceContract().sourceTypes())
                .containsExactly(
                        "external-secret-manager",
                        "environment-injected-secret",
                        "platform-managed-secret"
                );
        assertThat(evidence.productionSecretSourceContract().selectedSourceType())
                .isEqualTo("external-secret-manager");
        assertThat(evidence.productionSecretSourceContract().secretManagerOwner())
                .isEqualTo("platform-security-owner");
        assertThat(evidence.productionSecretSourceContract().rotationOwner())
                .isEqualTo("security-operations-owner");
        assertThat(evidence.productionSecretSourceContract().reviewCadence())
                .isEqualTo("quarterly-or-before-production-cutover");
        assertThat(evidence.productionSecretSourceContract().requiredConfirmationFields())
                .containsExactly(
                        "secret-manager-or-source-type",
                        "secret-manager-owner",
                        "rotation-owner",
                        "review-cadence",
                        "secret-value-access-boundary"
                );
        assertThat(evidence.productionSecretSourceContract().secretValueBoundaries())
                .containsExactly(
                        "contract-records-source-metadata-only",
                        "secret-values-must-not-be-read",
                        "secret-values-must-not-be-embedded-in-static-contracts",
                        "node-may-render-checklist-only"
                );
        assertThat(evidence.productionSecretSourceContract().nodeMayConsume()).isTrue();
        assertThat(evidence.productionSecretSourceContract().nodeMayReadSecretValues()).isFalse();
        assertThat(evidence.productionSecretSourceContract().requiresProductionSecrets()).isFalse();
        assertThat(evidence.productionSecretSourceContract().requiresProductionDatabase()).isFalse();
        assertThat(evidence.productionSecretSourceContract().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().contractVersion())
                .isEqualTo("java-production-deployment-runbook-contract.v1");
        assertThat(evidence.productionDeploymentRunbookContract().contractEndpoint())
                .isEqualTo("/contracts/production-deployment-runbook-contract.sample.json");
        assertThat(evidence.productionDeploymentRunbookContract().contractMode())
                .isEqualTo("READ_ONLY_DEPLOYMENT_RUNBOOK_CONTRACT");
        assertThat(evidence.productionDeploymentRunbookContract().deploymentWindowOwner())
                .isEqualTo("release-window-owner");
        assertThat(evidence.productionDeploymentRunbookContract().rollbackApprover())
                .isEqualTo("rollback-approval-owner");
        assertThat(evidence.productionDeploymentRunbookContract().databaseMigrationDirectionOptions())
                .containsExactly(
                        "forward-only",
                        "rollback-script-reviewed",
                        "no-database-change"
                );
        assertThat(evidence.productionDeploymentRunbookContract().selectedDatabaseMigrationDirection())
                .isEqualTo("no-database-change");
        assertThat(evidence.productionDeploymentRunbookContract().secretSourceConfirmation())
                .isEqualTo("/contracts/production-secret-source-contract.sample.json");
        assertThat(evidence.productionDeploymentRunbookContract().requiredConfirmationFields())
                .containsExactly(
                        "deployment-window-owner",
                        "rollback-approver",
                        "database-migration-direction",
                        "secret-source-confirmation",
                        "rollback-sql-review-gate",
                        "operator-approval-placeholder",
                        "release-audit-retention-fixture",
                        "release-operator-signoff-fixture",
                        "rollback-approver-evidence-fixture"
                );
        assertThat(evidence.productionDeploymentRunbookContract().runbookArtifacts())
                .containsExactly(
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-secret-source-contract.sample.json"
                );
        assertThat(evidence.productionDeploymentRunbookContract().nodeMayConsume()).isTrue();
        assertThat(evidence.productionDeploymentRunbookContract().nodeMayTriggerDeployment()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().nodeMayTriggerRollback()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().sqlExecutionAllowed()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().requiresProductionDatabase()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().requiresProductionSecrets()).isFalse();
        assertThat(evidence.productionDeploymentRunbookContract().changesOrderTransactionSemantics()).isFalse();
        assertThat(evidence.failedEventReplay().totalFailedEvents()).isEqualTo(4);
        assertThat(evidence.failedEventReplay().pendingReplayApprovals()).isEqualTo(2);
        assertThat(evidence.failedEventReplay().approvedReplayApprovals()).isEqualTo(1);
        assertThat(evidence.failedEventReplay().rejectedReplayApprovals()).isEqualTo(1);
        assertThat(evidence.failedEventReplay().replayBacklog()).isEqualTo(3);
        assertThat(evidence.failedEventReplay().latestFailedAt()).isEqualTo(latestFailedAt);
        assertThat(evidence.failedEventReplay().latestApprovalAt()).isEqualTo(latestApprovalAt);
        assertThat(evidence.failedEventReplay().realReplayAllowedByEvidence()).isFalse();
        assertThat(evidence.outbox().pendingEvents()).isEqualTo(6);
        assertThat(evidence.outbox().publisherEnabled()).isFalse();
        assertThat(evidence.outbox().rabbitMqEnabled()).isFalse();
        assertThat(evidence.outbox().blockers())
                .containsExactly("OUTBOX_PUBLISHER_DISABLED", "RABBITMQ_OUTBOX_DISABLED");
        assertThat(evidence.approvalExecution().requiredApprovalStatus()).isEqualTo("APPROVED");
        assertThat(evidence.approvalExecution().approvalRequired()).isTrue();
        assertThat(evidence.approvalExecution().dryRun()).isTrue();
        assertThat(evidence.approvalExecution().executionBlockers())
                .containsExactly(
                        "READ_ONLY_EVIDENCE_ENDPOINT",
                        "REPLAY_APPROVAL_PENDING",
                        "REPLAY_APPROVAL_REJECTED",
                        "REPLAY_BACKLOG_PRESENT"
                );
        assertThat(evidence.blockers())
                .contains(
                        "READ_ONLY_EVIDENCE_ENDPOINT",
                        "OUTBOX_PUBLISHER_DISABLED",
                        "RABBITMQ_OUTBOX_DISABLED"
                );
        assertThat(evidence.warnings())
                .containsExactly("OUTBOX_PENDING_EVENTS", "APPROVED_REPLAY_REQUIRES_DIGEST_CHECK");
        assertThat(evidence.evidenceEndpoints())
                .contains(
                        "/api/v1/ops/evidence",
                        "/api/v1/ops/release-approval-rehearsal",
                        "/contracts/ops-read-only-evidence.sample.json",
                        "/contracts/ops-evidence-field-guide.sample.json",
                        "/contracts/order-idempotency-boundary.sample.json",
                        "/contracts/order-idempotency-store-abstraction.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-handoff-checklist.fixture.json",
                        "/contracts/release-audit-retention.fixture.json",
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-handoff.sample.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/rollback-sql-review-gate.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/api/v1/failed-events/{id}/replay-execution-contract",
                        "/api/v1/failed-events/replay-evidence-index"
                );

        ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();
        assertThat(rehearsal.rehearsalVersion()).isEqualTo("java-release-approval-rehearsal.v1");
        assertThat(rehearsal.sourceEvidenceEndpoint()).isEqualTo("/api/v1/ops/evidence");
        assertThat(rehearsal.rehearsalMode()).isEqualTo("READ_ONLY_RELEASE_APPROVAL_REHEARSAL");
        assertThat(rehearsal.readOnly()).isTrue();
        assertThat(rehearsal.executionAllowed()).isFalse();
        assertThat(rehearsal.requestContext().contextVersion())
                .isEqualTo("java-release-approval-rehearsal-context.v1");
        assertThat(rehearsal.requestContext().requestId()).isEqualTo("rehearsal-request-id-not-supplied");
        assertThat(rehearsal.requestContext().requestIdSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.requestContext().operatorIdentity()).isEqualTo("operator-identity-not-supplied");
        assertThat(rehearsal.requestContext().operatorIdentitySource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.requestContext().auditCorrelationId()).isEqualTo("audit-correlation-id-not-supplied");
        assertThat(rehearsal.requestContext().auditCorrelationSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.requestContext().operatorAuthenticatedByJava()).isFalse();
        assertThat(rehearsal.requestContext().persistedByJava()).isFalse();
        assertThat(rehearsal.requestContext().approvalLedgerWritten()).isFalse();
        assertThat(rehearsal.requestContext().requiresProductionIdentityProvider()).isFalse();
        assertThat(rehearsal.requestContext().acceptedReadOnlyHeaders())
                .containsExactly(
                        "X-Rehearsal-Request-Id",
                        "X-Operator-Identity",
                        "X-Audit-Correlation-Id"
                );
        assertThat(rehearsal.requestContext().contextWarnings())
                .containsExactly(
                        "REHEARSAL_REQUEST_ID_MISSING",
                        "OPERATOR_IDENTITY_MISSING",
                        "AUDIT_CORRELATION_ID_MISSING"
                );
        assertThat(rehearsal.operatorWindowHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-operator-window-hint.v1");
        assertThat(rehearsal.operatorWindowHint().operatorId()).isEqualTo("orderops-operator-id-not-supplied");
        assertThat(rehearsal.operatorWindowHint().operatorIdSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.operatorWindowHint().operatorRoles()).isEqualTo("orderops-roles-not-supplied");
        assertThat(rehearsal.operatorWindowHint().operatorRolesSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.operatorWindowHint().operatorVerifiedClaim())
                .isEqualTo("orderops-operator-verified-not-supplied");
        assertThat(rehearsal.operatorWindowHint().operatorVerifiedClaimSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.operatorWindowHint().approvalCorrelationId())
                .isEqualTo("orderops-approval-correlation-id-not-supplied");
        assertThat(rehearsal.operatorWindowHint().approvalCorrelationIdSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.operatorWindowHint().operatorIdentityEchoed()).isFalse();
        assertThat(rehearsal.operatorWindowHint().operatorRolesEchoed()).isFalse();
        assertThat(rehearsal.operatorWindowHint().operatorVerifiedClaimEchoed()).isFalse();
        assertThat(rehearsal.operatorWindowHint().approvalCorrelationEchoed()).isFalse();
        assertThat(rehearsal.operatorWindowHint().operatorWindowContextComplete()).isFalse();
        assertThat(rehearsal.operatorWindowHint().productionIdpVerifiedByJava()).isFalse();
        assertThat(rehearsal.operatorWindowHint().persistedApprovalRecordByJava()).isFalse();
        assertThat(rehearsal.operatorWindowHint().nodeMayTreatAsProductionIdentity()).isFalse();
        assertThat(rehearsal.operatorWindowHint().acceptedOperatorWindowHeaders())
                .containsExactly(
                        "x-orderops-operator-id",
                        "x-orderops-roles",
                        "x-orderops-operator-verified",
                        "x-orderops-approval-correlation-id"
                );
        assertThat(rehearsal.operatorWindowHint().echoWarnings())
                .containsExactly(
                        "ORDEROPS_OPERATOR_ID_MISSING",
                        "ORDEROPS_OPERATOR_ROLES_MISSING",
                        "ORDEROPS_OPERATOR_VERIFIED_CLAIM_MISSING",
                        "ORDEROPS_APPROVAL_CORRELATION_ID_MISSING"
                );
        assertThat(rehearsal.operatorWindowHint().nodeVerificationActions())
                .contains(
                        "Compare operatorWindowHint.operatorId with Node v198 operatorIdentity.operatorId",
                        "Keep nodeMayTreatAsProductionIdentity=false"
                );
        assertThat(rehearsal.ciEvidenceHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-ci-evidence-hint.v1");
        assertThat(rehearsal.ciEvidenceHint().manifestProfileVersion())
                .isEqualTo("ci-manifest-profile-version-not-supplied");
        assertThat(rehearsal.ciEvidenceHint().manifestProfileVersionSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.ciEvidenceHint().manifestDigest()).isEqualTo("ci-manifest-digest-not-supplied");
        assertThat(rehearsal.ciEvidenceHint().manifestDigestSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.ciEvidenceHint().manifestEndpoint()).isEqualTo("ci-manifest-endpoint-not-supplied");
        assertThat(rehearsal.ciEvidenceHint().manifestEndpointSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.ciEvidenceHint().artifactRecordCount())
                .isEqualTo("ci-artifact-record-count-not-supplied");
        assertThat(rehearsal.ciEvidenceHint().artifactRecordCountSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.ciEvidenceHint().approvalCorrelationId())
                .isEqualTo("ci-approval-correlation-id-not-supplied");
        assertThat(rehearsal.ciEvidenceHint().approvalCorrelationIdSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.ciEvidenceHint().manifestProfileVersionEchoed()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().manifestDigestEchoed()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().manifestEndpointEchoed()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().artifactRecordCountEchoed()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().approvalCorrelationEchoed()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().ciEvidenceContextComplete()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().noLedgerWriteProof())
                .isEqualTo("NO_LEDGER_WRITE_PROOF_BY_RESPONSE_FIELDS");
        assertThat(rehearsal.ciEvidenceHint().noLedgerWriteProved()).isTrue();
        assertThat(rehearsal.ciEvidenceHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().productionWindowAllowedByJava()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().nodeMayTreatAsCiArtifactPublication()).isFalse();
        assertThat(rehearsal.ciEvidenceHint().acceptedCiEvidenceHeaders())
                .containsExactly(
                        "x-orderops-ci-manifest-version",
                        "x-orderops-ci-manifest-digest",
                        "x-orderops-ci-manifest-endpoint",
                        "x-orderops-ci-artifact-record-count",
                        "x-orderops-ci-approval-correlation-id"
                );
        assertThat(rehearsal.ciEvidenceHint().echoWarnings())
                .containsExactly(
                        "ORDEROPS_CI_MANIFEST_VERSION_MISSING",
                        "ORDEROPS_CI_MANIFEST_DIGEST_MISSING",
                        "ORDEROPS_CI_MANIFEST_ENDPOINT_MISSING",
                        "ORDEROPS_CI_ARTIFACT_RECORD_COUNT_MISSING",
                        "ORDEROPS_CI_APPROVAL_CORRELATION_ID_MISSING"
                );
        assertThat(rehearsal.ciEvidenceHint().nodeVerificationActions())
                .contains(
                        "Compare ciEvidenceHint.manifestDigest with Node v200 manifest.manifestDigest",
                        "Keep ciArtifactUploadedByJava=false and githubArtifactAccessedByJava=false"
                );
        assertThat(rehearsal.artifactRetentionHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-artifact-retention-hint.v1");
        assertThat(rehearsal.artifactRetentionHint().sourceRetentionFixtureVersion())
                .isEqualTo("java-release-audit-retention-fixture.v1");
        assertThat(rehearsal.artifactRetentionHint().sourceRetentionFixtureEndpoint())
                .isEqualTo("/contracts/release-audit-retention.fixture.json");
        assertThat(rehearsal.artifactRetentionHint().retentionId())
                .isEqualTo("release-retention-record-placeholder");
        assertThat(rehearsal.artifactRetentionHint().artifactTarget())
                .isEqualTo("release-tag-or-artifact-version-placeholder");
        assertThat(rehearsal.artifactRetentionHint().javaRetentionDays()).isEqualTo(180);
        assertThat(rehearsal.artifactRetentionHint().ciUploadContractVersion())
                .isEqualTo("ci-upload-contract-version-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciUploadContractVersionSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().ciUploadContractDigest())
                .isEqualTo("ci-upload-contract-digest-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciUploadContractDigestSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().ciArtifactName())
                .isEqualTo("ci-artifact-name-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciArtifactNameSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().ciArtifactRoot())
                .isEqualTo("ci-artifact-root-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciArtifactRootSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().ciRetentionDays())
                .isEqualTo("ci-retention-days-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciRetentionDaysSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().ciUploadMode())
                .isEqualTo("ci-upload-mode-not-supplied");
        assertThat(rehearsal.artifactRetentionHint().ciUploadModeSource()).isEqualTo("NOT_SUPPLIED");
        assertThat(rehearsal.artifactRetentionHint().uploadContractVersionEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().uploadContractDigestEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().artifactNameEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().artifactRootEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().retentionDaysEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().uploadModeEchoed()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().artifactRetentionContextComplete()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().retentionDaysWithinJavaRetention()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().javaRetentionFixtureReadOnly()).isTrue();
        assertThat(rehearsal.artifactRetentionHint().auditExportReadOnly()).isTrue();
        assertThat(rehearsal.artifactRetentionHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().productionWindowAllowedByJava()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().nodeMayTreatAsRetentionAuthorization()).isFalse();
        assertThat(rehearsal.artifactRetentionHint().acceptedArtifactRetentionHeaders())
                .containsExactly(
                        "x-orderops-ci-upload-contract-version",
                        "x-orderops-ci-upload-contract-digest",
                        "x-orderops-ci-artifact-name",
                        "x-orderops-ci-artifact-root",
                        "x-orderops-ci-retention-days",
                        "x-orderops-ci-upload-mode"
                );
        assertThat(rehearsal.artifactRetentionHint().releaseEvidenceEndpoints())
                .contains(
                        "/api/v1/ops/evidence",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/release-bundle-manifest.sample.json"
                );
        assertThat(rehearsal.artifactRetentionHint().echoWarnings())
                .containsExactly(
                        "ORDEROPS_CI_UPLOAD_CONTRACT_VERSION_MISSING",
                        "ORDEROPS_CI_UPLOAD_CONTRACT_DIGEST_MISSING",
                        "ORDEROPS_CI_ARTIFACT_NAME_MISSING",
                        "ORDEROPS_CI_ARTIFACT_ROOT_MISSING",
                        "ORDEROPS_CI_RETENTION_DAYS_MISSING",
                        "ORDEROPS_CI_UPLOAD_MODE_MISSING"
                );
        assertThat(rehearsal.artifactRetentionHint().nodeVerificationActions())
                .contains(
                        "Compare artifactRetentionHint.ciUploadContractDigest with Node v202 dryRunContract.contractDigest",
                        "Require artifactRetentionHint.retentionDaysWithinJavaRetention=true before Node v203 retention gate",
                        "Keep ciArtifactUploadedByJava=false and githubArtifactAccessedByJava=false"
                );
        assertThat(rehearsal.failureTaxonomy().taxonomyVersion())
                .isEqualTo("java-release-approval-rehearsal-failure-taxonomy.v1");
        assertThat(rehearsal.failureTaxonomy().upstreamReadiness()).isEqualTo("READY");
        assertThat(rehearsal.failureTaxonomy().authContextReadiness()).isEqualTo("WARNING");
        assertThat(rehearsal.failureTaxonomy().auditCorrelationReadiness()).isEqualTo("WARNING");
        assertThat(rehearsal.failureTaxonomy().javaReadOnlyUpstreamReady()).isTrue();
        assertThat(rehearsal.failureTaxonomy().authContextComplete()).isFalse();
        assertThat(rehearsal.failureTaxonomy().auditCorrelationPresent()).isFalse();
        assertThat(rehearsal.failureTaxonomy().retryableByReadOnlyAdapter()).isTrue();
        assertThat(rehearsal.failureTaxonomy().writeActionRequired()).isFalse();
        assertThat(rehearsal.failureTaxonomy().failureCategories())
                .containsExactly(
                        "AUTH_CONTEXT_WARNING",
                        "AUDIT_CORRELATION_WARNING",
                        "READ_ONLY_EXECUTION_BLOCKED"
                );
        assertThat(rehearsal.failureTaxonomy().taxonomyWarnings())
                .containsExactly(
                        "REQUEST_ID_OR_OPERATOR_IDENTITY_MISSING",
                        "AUDIT_CORRELATION_ID_MISSING",
                        "REHEARSAL_REMAINS_READ_ONLY"
                );
        assertThat(rehearsal.verificationHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-verification-hint.v1");
        assertThat(rehearsal.verificationHint().responseSchemaVersion())
                .isEqualTo("java-release-approval-rehearsal-response-schema.v6");
        assertThat(rehearsal.verificationHint().warningDigest()).startsWith("sha256:");
        assertThat(rehearsal.verificationHint().noLedgerWriteProof())
                .isEqualTo("NO_LEDGER_WRITE_PROOF_BY_RESPONSE_FIELDS");
        assertThat(rehearsal.verificationHint().noLedgerWriteProved()).isTrue();
        assertThat(rehearsal.verificationHint().nodeMayTreatAsProductionAuthorization()).isFalse();
        assertThat(rehearsal.verificationHint().schemaFields())
                .contains(
                        "requestContext",
                        "operatorWindowHint",
                        "ciEvidenceHint",
                        "artifactRetentionHint",
                        "failureTaxonomy",
                        "verificationHint",
                        "executionBoundaries"
                );
        assertThat(rehearsal.verificationHint().warningDigestInputs())
                .containsExactly(
                        "contextWarnings",
                        "operatorWindowEchoWarnings",
                        "ciEvidenceEchoWarnings",
                        "artifactRetentionEchoWarnings",
                        "failureCategories",
                        "taxonomyWarnings",
                        "executionAllowed",
                        "approvalLedgerWritten",
                        "nodeMayWriteApprovalLedger"
                );
        assertThat(rehearsal.verificationHint().proofClaims())
                .contains(
                        "executionAllowed=false",
                        "requestContext.approvalLedgerWritten=false",
                        "ciEvidenceHint.noLedgerWriteProved=true",
                        "ciEvidenceHint.ciArtifactUploadedByJava=false",
                        "artifactRetentionHint.javaRetentionFixtureReadOnly=true",
                        "artifactRetentionHint.githubArtifactAccessedByJava=false",
                        "executionBoundaries.nodeMayWriteApprovalLedger=false"
                );
        assertThat(rehearsal.verificationHint().nodeVerificationActions())
                .contains(
                        "Verify responseSchemaVersion before importing operator window results",
                        "Compare ciEvidenceHint.manifestDigest with Node v200 manifest.manifestDigest",
                        "Compare artifactRetentionHint.ciArtifactName and ciRetentionDays with Node v202 dry-run contract",
                        "Keep UPSTREAM_ACTIONS_ENABLED=false"
                );
        assertThat(rehearsal.releaseApprovalInputs().releaseOperatorSignoffFixtureEndpoint())
                .isEqualTo("/contracts/release-operator-signoff.fixture.json");
        assertThat(rehearsal.releaseApprovalInputs().rollbackApproverEvidenceFixtureEndpoint())
                .isEqualTo("/contracts/rollback-approver-evidence.fixture.json");
        assertThat(rehearsal.releaseApprovalInputs().rollbackApprovalRecordFixtureEndpoint())
                .isEqualTo("/contracts/rollback-approval-record.fixture.json");
        assertThat(rehearsal.releaseApprovalInputs().releaseBundleManifestEndpoint())
                .isEqualTo("/contracts/release-bundle-manifest.sample.json");
        assertThat(rehearsal.releaseApprovalInputs().requiredEvidenceEndpoints())
                .containsExactly(
                        "/contracts/release-operator-signoff.fixture.json",
                        "/contracts/rollback-approver-evidence.fixture.json",
                        "/contracts/rollback-approval-record.fixture.json",
                        "/contracts/release-bundle-manifest.sample.json",
                        "/contracts/release-verification-manifest.sample.json",
                        "/contracts/deployment-rollback-evidence.sample.json",
                        "/contracts/production-deployment-runbook-contract.sample.json",
                        "/contracts/production-secret-source-contract.sample.json",
                        "/contracts/rollback-sql-review-gate.sample.json"
                );
        assertThat(rehearsal.liveSignals().pendingReplayApprovals()).isEqualTo(2);
        assertThat(rehearsal.liveSignals().approvedReplayApprovals()).isEqualTo(1);
        assertThat(rehearsal.liveSignals().rejectedReplayApprovals()).isEqualTo(1);
        assertThat(rehearsal.liveSignals().replayBacklog()).isEqualTo(3);
        assertThat(rehearsal.liveSignals().pendingOutboxEvents()).isEqualTo(6);
        assertThat(rehearsal.liveSignals().realReplayAllowedByEvidence()).isFalse();
        assertThat(rehearsal.liveSignals().approvalExecutionDryRun()).isTrue();
        assertThat(rehearsal.liveSignals().evidenceExecutionAllowed()).isFalse();
        assertThat(rehearsal.executionBoundaries().nodeMayConsume()).isTrue();
        assertThat(rehearsal.executionBoundaries().nodeMayCreateApprovalDecision()).isFalse();
        assertThat(rehearsal.executionBoundaries().nodeMayWriteApprovalLedger()).isFalse();
        assertThat(rehearsal.executionBoundaries().nodeMayTriggerDeployment()).isFalse();
        assertThat(rehearsal.executionBoundaries().nodeMayTriggerRollback()).isFalse();
        assertThat(rehearsal.executionBoundaries().nodeMayExecuteRollbackSql()).isFalse();
        assertThat(rehearsal.executionBoundaries().requiresProductionDatabase()).isFalse();
        assertThat(rehearsal.executionBoundaries().requiresProductionSecrets()).isFalse();
        assertThat(rehearsal.executionBoundaries().changesOrderTransactionSemantics()).isFalse();
        assertThat(rehearsal.rehearsalBlockers())
                .contains(
                        "READ_ONLY_RELEASE_APPROVAL_REHEARSAL",
                        "APPROVAL_DECISION_CREATION_DISABLED",
                        "ROLLBACK_SQL_EXECUTION_DISABLED",
                        "REPLAY_APPROVAL_PENDING"
                );
        assertThat(rehearsal.requiredNodeEnvironment())
                .containsExactly("UPSTREAM_PROBES_ENABLED=true", "UPSTREAM_ACTIONS_ENABLED=false");
        assertThat(rehearsal.nextEvidenceActions())
                .containsExactly(
                        "GET /api/v1/ops/evidence",
                        "GET /api/v1/ops/release-approval-rehearsal",
                        "GET /contracts/release-operator-signoff.fixture.json",
                        "GET /contracts/rollback-approver-evidence.fixture.json",
                        "GET /contracts/rollback-approval-record.fixture.json",
                        "Keep UPSTREAM_ACTIONS_ENABLED=false"
                );

        ReleaseApprovalRehearsalResponse headerBackedRehearsal = service.releaseApprovalRehearsal(
                " rehearsal-v67-001 ",
                " release-operator@example.test ",
                " audit-correlation-v67 ",
                " operator-198 ",
                " operator,auditor ",
                " true ",
                " approval-v198-operator-window ",
                " real-read-window-ci-archive-artifact-manifest.v1 ",
                " sha256:node-v200-manifest-digest ",
                " /api/v1/production/real-read-window-ci-archive-artifact-manifest ",
                " 9 ",
                " approval-v198-operator-window ",
                " real-read-window-ci-artifact-upload-dry-run-contract.v1 ",
                " sha256:node-v202-upload-contract-digest ",
                " orderops-real-read-window-evidence-v191-v201 ",
                " c/ ",
                " 30 ",
                " dry-run-contract-only "
        );
        assertThat(headerBackedRehearsal.requestContext().requestId()).isEqualTo("rehearsal-v67-001");
        assertThat(headerBackedRehearsal.requestContext().requestIdSource())
                .isEqualTo("X-Rehearsal-Request-Id");
        assertThat(headerBackedRehearsal.requestContext().operatorIdentity())
                .isEqualTo("release-operator@example.test");
        assertThat(headerBackedRehearsal.requestContext().operatorIdentitySource())
                .isEqualTo("X-Operator-Identity");
        assertThat(headerBackedRehearsal.requestContext().auditCorrelationId())
                .isEqualTo("audit-correlation-v67");
        assertThat(headerBackedRehearsal.requestContext().auditCorrelationSource())
                .isEqualTo("X-Audit-Correlation-Id");
        assertThat(headerBackedRehearsal.requestContext().contextWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorId()).isEqualTo("operator-198");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdSource())
                .isEqualTo("x-orderops-operator-id");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRoles()).isEqualTo("operator,auditor");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesSource())
                .isEqualTo("x-orderops-roles");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaim()).isEqualTo("true");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimSource())
                .isEqualTo("x-orderops-operator-verified");
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationId())
                .isEqualTo("approval-v198-operator-window");
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationIdSource())
                .isEqualTo("x-orderops-approval-correlation-id");
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorIdentityEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorRolesEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorVerifiedClaimEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().approvalCorrelationEchoed()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().operatorWindowContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.operatorWindowHint().productionIdpVerifiedByJava()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().persistedApprovalRecordByJava()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().nodeMayTreatAsProductionIdentity()).isFalse();
        assertThat(headerBackedRehearsal.operatorWindowHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersion())
                .isEqualTo("real-read-window-ci-archive-artifact-manifest.v1");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionSource())
                .isEqualTo("x-orderops-ci-manifest-version");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigest())
                .isEqualTo("sha256:node-v200-manifest-digest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestSource())
                .isEqualTo("x-orderops-ci-manifest-digest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpoint())
                .isEqualTo("/api/v1/production/real-read-window-ci-archive-artifact-manifest");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointSource())
                .isEqualTo("x-orderops-ci-manifest-endpoint");
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCount()).isEqualTo("9");
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountSource())
                .isEqualTo("x-orderops-ci-artifact-record-count");
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationId())
                .isEqualTo("approval-v198-operator-window");
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationIdSource())
                .isEqualTo("x-orderops-ci-approval-correlation-id");
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestProfileVersionEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestDigestEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().manifestEndpointEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().artifactRecordCountEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().approvalCorrelationEchoed()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().ciEvidenceContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().noLedgerWriteProved()).isTrue();
        assertThat(headerBackedRehearsal.ciEvidenceHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().productionWindowAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().nodeMayTreatAsCiArtifactPublication()).isFalse();
        assertThat(headerBackedRehearsal.ciEvidenceHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersion())
                .isEqualTo("real-read-window-ci-artifact-upload-dry-run-contract.v1");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractVersionSource())
                .isEqualTo("x-orderops-ci-upload-contract-version");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigest())
                .isEqualTo("sha256:node-v202-upload-contract-digest");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadContractDigestSource())
                .isEqualTo("x-orderops-ci-upload-contract-digest");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactName())
                .isEqualTo("orderops-real-read-window-evidence-v191-v201");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactNameSource())
                .isEqualTo("x-orderops-ci-artifact-name");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRoot()).isEqualTo("c/");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactRootSource())
                .isEqualTo("x-orderops-ci-artifact-root");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDays()).isEqualTo("30");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciRetentionDaysSource())
                .isEqualTo("x-orderops-ci-retention-days");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadMode())
                .isEqualTo("dry-run-contract-only");
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciUploadModeSource())
                .isEqualTo("x-orderops-ci-upload-mode");
        assertThat(headerBackedRehearsal.artifactRetentionHint().artifactRetentionContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().retentionDaysWithinJavaRetention()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().javaRetentionFixtureReadOnly()).isTrue();
        assertThat(headerBackedRehearsal.artifactRetentionHint().ciArtifactUploadedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().githubArtifactAccessedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().productionWindowAllowedByJava()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().nodeMayTreatAsRetentionAuthorization()).isFalse();
        assertThat(headerBackedRehearsal.artifactRetentionHint().echoWarnings()).isEmpty();
        assertThat(headerBackedRehearsal.failureTaxonomy().upstreamReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().authContextReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationReadiness()).isEqualTo("READY");
        assertThat(headerBackedRehearsal.failureTaxonomy().authContextComplete()).isTrue();
        assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationPresent()).isTrue();
        assertThat(headerBackedRehearsal.failureTaxonomy().failureCategories())
                .containsExactly("READ_ONLY_EXECUTION_BLOCKED");
        assertThat(headerBackedRehearsal.failureTaxonomy().taxonomyWarnings())
                .containsExactly("REHEARSAL_REMAINS_READ_ONLY");
        assertThat(headerBackedRehearsal.verificationHint().hintVersion())
                .isEqualTo("java-release-approval-rehearsal-verification-hint.v1");
        assertThat(headerBackedRehearsal.verificationHint().responseSchemaVersion())
                .isEqualTo("java-release-approval-rehearsal-response-schema.v6");
        assertThat(headerBackedRehearsal.verificationHint().warningDigest()).startsWith("sha256:");
        assertThat(headerBackedRehearsal.verificationHint().warningDigest())
                .isNotEqualTo(rehearsal.verificationHint().warningDigest());
        ReleaseApprovalRehearsalResponse repeatedHeaderBackedRehearsal = service.releaseApprovalRehearsal(
                "rehearsal-v67-001",
                "release-operator@example.test",
                "audit-correlation-v67",
                "operator-198",
                "operator,auditor",
                "true",
                "approval-v198-operator-window",
                "real-read-window-ci-archive-artifact-manifest.v1",
                "sha256:node-v200-manifest-digest",
                "/api/v1/production/real-read-window-ci-archive-artifact-manifest",
                "9",
                "approval-v198-operator-window",
                "real-read-window-ci-artifact-upload-dry-run-contract.v1",
                "sha256:node-v202-upload-contract-digest",
                "orderops-real-read-window-evidence-v191-v201",
                "c/",
                "30",
                "dry-run-contract-only"
        );
        assertThat(repeatedHeaderBackedRehearsal.verificationHint().warningDigest())
                .isEqualTo(headerBackedRehearsal.verificationHint().warningDigest());
        assertThat(headerBackedRehearsal.verificationHint().noLedgerWriteProved()).isTrue();
        assertThat(headerBackedRehearsal.verificationHint().nodeMayTreatAsProductionAuthorization()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().operatorAuthenticatedByJava()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().persistedByJava()).isFalse();
        assertThat(headerBackedRehearsal.requestContext().approvalLedgerWritten()).isFalse();
        assertThat(headerBackedRehearsal.executionAllowed()).isFalse();
        assertThat(headerBackedRehearsal.executionBoundaries().nodeMayWriteApprovalLedger()).isFalse();
    }
}
