package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Map;
import org.junit.jupiter.api.Test;

class OpsShardReadinessRoutePathsTests {

    @Test
    void evidenceServiceEndpointsUseSharedRouteConstants() {
        assertThat(Map.ofEntries(
                Map.entry(
                        OpsShardReadinessRoutePaths.READ_ONLY_EVIDENCE_CATALOG,
                        OpsShardReadinessReadOnlyEvidenceCatalogService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.READ_ONLY_EVIDENCE_CATALOG_HANDOFF,
                        OpsShardReadinessReadOnlyEvidenceCatalogHandoffService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.READ_ONLY_EVIDENCE_CATALOG_HANDOFF_VERIFICATION,
                        OpsShardReadinessReadOnlyEvidenceCatalogHandoffVerificationService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.READ_ONLY_ENDPOINT_REGISTRY_INTEGRITY,
                        OpsShardReadinessReadOnlyEndpointRegistryIntegrityService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.EVIDENCE_INDEX,
                        OpsShardReadinessEvidenceIndexService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.EVIDENCE_VERIFICATION,
                        OpsShardReadinessEvidenceVerificationService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.EVIDENCE_HANDOFF,
                        OpsShardReadinessEvidenceHandoffService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_ALIGNMENT,
                        OpsShardReadinessV1ContractAlignmentService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_ALIGNMENT_HANDOFF,
                        OpsShardReadinessV1ContractAlignmentHandoffService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_EVIDENCE_PACKET,
                        OpsShardReadinessV1ContractEvidencePacketService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_OPERATOR_CHECKLIST,
                        OpsShardReadinessV1ContractOperatorChecklistService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_HANDOFF_MANIFEST,
                        OpsShardReadinessV1ContractHandoffManifestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_CONSUMER_PROBE_PLAN,
                        OpsShardReadinessV1ContractConsumerProbePlanService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_ENDPOINT_CATALOG,
                        OpsShardReadinessV1ContractEndpointCatalogService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_CONSUMER_HANDOFF_BUNDLE,
                        OpsShardReadinessV1ContractConsumerHandoffBundleService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_CONSUMER_VERIFICATION_CHECKLIST,
                        OpsShardReadinessV1ContractConsumerVerificationChecklistService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_CONSUMER_EVIDENCE_DIGEST,
                        OpsShardReadinessV1ContractConsumerEvidenceDigestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.V1_CONTRACT_CONSUMER_READINESS_HANDOFF,
                        OpsShardReadinessV1ContractConsumerReadinessHandoffService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_CATALOG,
                        OpsShardReadinessPrototypeEvidenceService.CATALOG_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_FIXTURE_ECHO,
                        OpsShardReadinessPrototypeEvidenceService.FIXTURE_ECHO_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_FIELD_ALIGNMENT,
                        OpsShardReadinessPrototypeEvidenceService.FIELD_ALIGNMENT_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_READ_ONLY_INTEGRATION_BRIDGE,
                        OpsShardReadinessPrototypeEvidenceService.READ_ONLY_INTEGRATION_BRIDGE_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_ROUTE_CLEANUP_BRIDGE,
                        OpsShardReadinessPrototypeEvidenceService.ROUTE_CLEANUP_BRIDGE_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_READ_WINDOW_HANDOFF,
                        OpsShardReadinessPrototypeEvidenceService.READ_WINDOW_HANDOFF_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_CONSUMER_GATE_PACKET,
                        OpsShardReadinessPrototypeEvidenceService.CONSUMER_GATE_PACKET_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_OPERATOR_CI_HANDOFF,
                        OpsShardReadinessPrototypeEvidenceService.OPERATOR_CI_HANDOFF_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_AUDIT_DIGEST,
                        OpsShardReadinessPrototypeEvidenceService.AUDIT_DIGEST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_CLOSEOUT,
                        OpsShardReadinessPrototypeEvidenceService.CLOSEOUT_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_CATALOG,
                        OpsShardReadinessPrototypeHandoffService.CATALOG_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_ENDPOINT_INVENTORY,
                        OpsShardReadinessPrototypeHandoffService.ENDPOINT_INVENTORY_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_BOUNDARY_MATRIX,
                        OpsShardReadinessPrototypeHandoffService.BOUNDARY_MATRIX_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths
                                .SHARD_READINESS_PROTOTYPE_HANDOFF_CONSUMER_VERIFICATION_CHECKLIST,
                        OpsShardReadinessPrototypeHandoffService.CONSUMER_VERIFICATION_CHECKLIST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_READ_WINDOW_CHECKLIST,
                        OpsShardReadinessPrototypeHandoffService.READ_WINDOW_CHECKLIST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_DIGEST_MANIFEST,
                        OpsShardReadinessPrototypeHandoffService.DIGEST_MANIFEST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_CI_MANIFEST,
                        OpsShardReadinessPrototypeHandoffService.CI_MANIFEST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_ARCHIVE_MANIFEST,
                        OpsShardReadinessPrototypeHandoffService.ARCHIVE_MANIFEST_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths
                                .SHARD_READINESS_PROTOTYPE_HANDOFF_OPERATOR_SIGNOFF_PACKET,
                        OpsShardReadinessPrototypeHandoffService.OPERATOR_SIGNOFF_PACKET_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.SHARD_READINESS_PROTOTYPE_HANDOFF_CLOSEOUT,
                        OpsShardReadinessPrototypeHandoffService.CLOSEOUT_ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_EVIDENCE_CATALOG,
                        OpsShardReadinessRouteCleanupEvidenceService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_PHASE_SUMMARY,
                        OpsShardReadinessRouteCleanupPhaseSummaryService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_BOUNDARY_MATRIX,
                        OpsShardReadinessRouteCleanupBoundaryMatrixService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_HANDOFF_CHECKLIST,
                        OpsShardReadinessRouteCleanupHandoffChecklistService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_ARCHIVE_PLAN,
                        OpsShardReadinessRouteCleanupArchivePlanService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_DIGEST,
                        OpsShardReadinessRouteCleanupDigestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_SOURCE_PLAN_ALIGNMENT,
                        OpsShardReadinessRouteCleanupSourcePlanAlignmentService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_RELEASE_HANDOFF,
                        OpsShardReadinessRouteCleanupReleaseHandoffService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_OPERATOR_RUNBOOK,
                        OpsShardReadinessRouteCleanupOperatorRunbookService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_READ_ONLY_GATE,
                        OpsShardReadinessRouteCleanupReadOnlyGateService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_SUITE_CLOSEOUT,
                        OpsShardReadinessRouteCleanupSuiteCloseoutService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_ARCHIVE_VERIFICATION,
                        OpsShardReadinessRouteCleanupArchiveVerificationService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CONSUMER_PACKET,
                        OpsShardReadinessRouteCleanupConsumerPacketService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CI_EVIDENCE,
                        OpsShardReadinessRouteCleanupCiEvidenceService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_ENDPOINT_MANIFEST,
                        OpsShardReadinessRouteCleanupEndpointManifestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_REGRESSION_GUARD,
                        OpsShardReadinessRouteCleanupRegressionGuardService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_HANDOFF_BUNDLE,
                        OpsShardReadinessRouteCleanupHandoffBundleService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CONTINUITY_REPORT,
                        OpsShardReadinessRouteCleanupContinuityReportService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CONSUMER_CHECKLIST,
                        OpsShardReadinessRouteCleanupConsumerChecklistService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_FINAL_DIGEST,
                        OpsShardReadinessRouteCleanupFinalDigestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_EXTENDED_CLOSEOUT,
                        OpsShardReadinessRouteCleanupExtendedCloseoutService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_AUDIT_TRAIL,
                        OpsShardReadinessRouteCleanupAuditTrailService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_ACCEPTANCE_RECEIPT,
                        OpsShardReadinessRouteCleanupAcceptanceReceiptService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_EVIDENCE_REGISTER,
                        OpsShardReadinessRouteCleanupEvidenceRegisterService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_OPERATIONAL_SNAPSHOT,
                        OpsShardReadinessRouteCleanupOperationalSnapshotService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_POLICY_GUARD,
                        OpsShardReadinessRouteCleanupPolicyGuardService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_REVIEWER_PACKET,
                        OpsShardReadinessRouteCleanupReviewerPacketService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_TRANSITION_BRIEF,
                        OpsShardReadinessRouteCleanupTransitionBriefService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_FINAL_VERIFICATION,
                        OpsShardReadinessRouteCleanupFinalVerificationService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_FINAL_ARCHIVE_PLAN,
                        OpsShardReadinessRouteCleanupFinalArchivePlanService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_THIRD_RUN_CLOSEOUT,
                        OpsShardReadinessRouteCleanupThirdRunCloseoutService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_COMPLETION_INDEX,
                        OpsShardReadinessRouteCleanupCompletionIndexService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_COMPLETION_CERTIFICATE,
                        OpsShardReadinessRouteCleanupCompletionCertificateService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_POST_PUSH_CLOSEOUT,
                        OpsShardReadinessRouteCleanupPostPushCloseoutService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CI_RUN_ATTESTATION,
                        OpsShardReadinessRouteCleanupCiRunAttestationService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_TAG_MANIFEST,
                        OpsShardReadinessRouteCleanupTagManifestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_RELEASE_EVIDENCE_BUNDLE,
                        OpsShardReadinessRouteCleanupReleaseEvidenceBundleService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_CONSUMER_SIGNOFF_PACKET,
                        OpsShardReadinessRouteCleanupConsumerSignoffPacketService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_ARCHIVE_HANDOFF_RECEIPT,
                        OpsShardReadinessRouteCleanupArchiveHandoffReceiptService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_MAINTENANCE_BOUNDARY_REPORT,
                        OpsShardReadinessRouteCleanupMaintenanceBoundaryReportService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_FIXTURE_COVERAGE_INDEX,
                        OpsShardReadinessRouteCleanupFixtureCoverageIndexService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_COMPLETION_AUDIT_DIGEST,
                        OpsShardReadinessRouteCleanupCompletionAuditDigestService.ENDPOINT
                ),
                Map.entry(
                        OpsShardReadinessRoutePaths.ROUTE_CLEANUP_POST_COMPLETION_CLOSEOUT,
                        OpsShardReadinessRouteCleanupPostCompletionCloseoutService.ENDPOINT
                )
        )).allSatisfy((route, endpoint) ->
                assertThat(endpoint).isEqualTo(OpsShardReadinessRoutePaths.BASE_PATH + route));
    }
}
