package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalResponse;
import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalTestSupport;
import org.junit.jupiter.api.Test;

class ReleaseAuditGuardTests extends ReleaseApprovalRehearsalTestSupport {

  @Test
  void buildsManagedAuditGuardOverviewForHeaderBackedRequest() {
    OpsEvidenceService service = readOnlyFixtureService();
    ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();

    ReleaseApprovalRehearsalResponse headerBackedRehearsal =
        service.releaseApprovalRehearsal(paddedHeaderBackedRehearsalRequest());
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayWriteLocalDryRunFiles())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayConnectManagedAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayCreateApprovalDecision())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayWriteApprovalLedger())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayPersistApprovalRecord())
        .isFalse();
    assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayExecuteSql())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeV215MayTriggerDeployment())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayTriggerRollback())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().nodeV215MayExecuteRestore())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .javaApprovalDecisionCreated())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().javaApprovalLedgerWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .javaApprovalRecordPersisted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .javaManagedAuditWriteExecuted())
        .isFalse();
    assertThat(headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterBoundaryReceipt().readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterBoundaryReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForNodeV217ProductionHardeningReadinessGate())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .receiptWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .operatorIdentityPrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .approvalDecisionSourcePrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .ledgerHandoffPrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .retentionOwnerPrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .failureHandlingPrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .rollbackReviewPrerequisiteDocumented())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaCreatesApprovalDecision())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaWritesApprovalLedger())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaWritesManagedAuditStore())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaExecutesSql())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaTriggersDeployment())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaTriggersRollback())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .javaExecutesRestore())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayConnectManagedAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayWriteApprovalLedger())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayExecuteSql())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayTriggerDeployment())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayTriggerRollback())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeV217MayExecuteRestore())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .readyForProductionOperations())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditProductionAdapterPrerequisiteReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .opsEvidenceServiceQualitySplitReceipt()
                .readyForNodeV219ImplementationPrecheck())
        .isTrue();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().receiptWarnings())
        .isEmpty();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().nodeV219MayConsume())
        .isTrue();
    assertThat(
            headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().firstSafeSplitApplied())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .opsEvidenceServiceQualitySplitReceipt()
                .broadServiceSplitDeferred())
        .isTrue();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().apiShapeChanged())
        .isFalse();
    assertThat(
            headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalDecisionCreated())
        .isFalse();
    assertThat(
            headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalLedgerWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().approvalRecordPersisted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .opsEvidenceServiceQualitySplitReceipt()
                .managedAuditStoreWritten())
        .isFalse();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().sqlExecuted())
        .isFalse();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().deploymentTriggered())
        .isFalse();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().rollbackTriggered())
        .isFalse();
    assertThat(headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().restoreExecuted())
        .isFalse();
    assertThat(
            headerBackedRehearsal.opsEvidenceServiceQualitySplitReceipt().readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .opsEvidenceServiceQualitySplitReceipt()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .opsEvidenceServiceQualitySplitReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .readyForNodeV221LocalAdapterCandidateDryRun())
        .isTrue();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .consumedByNodeDisabledShellProfile())
        .isEqualTo("managed-audit-adapter-disabled-shell.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeV220SelectedAdapterDisabled())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeV220LocalDryRunOnlyDeclared())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeV220AppendWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeV220ExternalManagedAuditAccessed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeV220LocalDryRunWritePerformed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaApprovalDecisionCreated())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaApprovalLedgerWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaApprovalRecordPersisted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaManagedAuditStoreWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().javaSqlExecuted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaDeploymentTriggered())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaRollbackTriggered())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .javaRestoreExecuted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardDigest())
        .startsWith("sha256:");
  }
}
