package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalResponse;
import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalTestSupport;
import org.junit.jupiter.api.Test;

class ReleaseHeaderBoundaryTests extends ReleaseApprovalRehearsalTestSupport {

  @Test
  void buildsExternalBoundaryOverviewForHeaderBackedRequest() {
    OpsEvidenceService service = readOnlyFixtureService();
    ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();

    ReleaseApprovalRehearsalResponse headerBackedRehearsal =
        service.releaseApprovalRehearsal(paddedHeaderBackedRehearsalRequest());
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForNodeV223ExternalAdapterConnectionReadinessReview())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .guardWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .consumedByNodeVerificationReportProfile())
        .isEqualTo("managed-audit-local-adapter-candidate-verification-report.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222ReadOnlyReport())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222SourceEndpointRerunPerformed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222AdditionalLocalDryRunWritePerformed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeV222ConnectsManagedAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .ownerApprovalRequiredBeforeConnection())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .schemaMigrationReviewRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .credentialReviewRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .externalManagedAuditConnectionOpened())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .externalManagedAuditSchemaMigrated())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .javaApprovalLedgerWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .javaManagedAuditStoreWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .javaSqlExecuted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForNodeV225SandboxAdapterDryRunPackage())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .guardWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .consumedByNodeSandboxPlanProfile())
        .isEqualTo("managed-audit-sandbox-adapter-dry-run-plan.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeV224SandboxPlan()
                .readOnlyPlan())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeV224SandboxPlan()
                .connectsManagedAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .ownerApprovalBoundary()
                .ownerApprovalArtifactRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .ownerApprovalBoundary()
                .ownerApprovalArtifactProvidedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .schemaRehearsalBoundary()
                .schemaMigrationExecutionAllowed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .credentialBoundary()
                .sandboxCredentialHandleRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary()
                .externalManagedAuditConnectionOpened())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary()
                .javaManagedAuditStoreWritten())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .executionBoundary()
                .javaSqlExecuted())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary()
                .builderClassName())
        .isEqualTo("ReleaseApprovalManagedAuditSandboxAdapterApprovalSchemaGuardReceiptBuilder");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary()
                .builderOrHelperSplitApplied())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .qualityGateBoundary()
                .longBooleanConstructorAvoided())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForProductionAudit())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .readyForProductionWindow())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .guardDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForNodeV229ManualSandboxConnectionPacketVerification())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .markerWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .consumedByNodeOperatorPacketProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-operator-packet.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .manualSandboxConnectionWindowRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .manualSandboxConnectionWindowOpenedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .sandboxConnectionWindowBoundary()
                .connectionExecutionAllowed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .ownerApprovalArtifactIdFieldRecognizedByJava())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .operatorPacketBoundary()
                .schemaRehearsalIdFieldRecognizedByJava())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialHandleNameRecognizedByJava())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .rollbackPathBoundary()
                .rollbackExecutionAllowedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary()
                .externalManagedAuditConnectionOpenedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .javaExecutionBoundary()
                .sqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .markerDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForNodeV231ManualSandboxConnectionPreflightVerification())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .markerWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .consumedByNodePreflightGateProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-preflight-gate.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowFlagName())
        .isEqualTo("ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED");
  }
}
