package com.codexdemo.orderplatform.ops;

import static org.assertj.core.api.Assertions.assertThat;

import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalResponse;
import com.codexdemo.orderplatform.ops.maintenance.releaseapproval.ReleaseApprovalRehearsalTestSupport;
import org.junit.jupiter.api.Test;

class ReleaseSandboxHandoffTests extends ReleaseApprovalRehearsalTestSupport {

  @Test
  void buildsSandboxHandoffOverviewForHeaderBackedRequest() {
    OpsEvidenceService service = readOnlyFixtureService();
    ReleaseApprovalRehearsalResponse rehearsal = service.releaseApprovalRehearsal();

    ReleaseApprovalRehearsalResponse headerBackedRehearsal =
        service.releaseApprovalRehearsal(paddedHeaderBackedRehearsalRequest());
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowOpenByDefault())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .manualWindowOpenedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .sandboxConnectionWindowBoundary()
                .nodeAutoStartAllowed())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .allRequiredPreflightFieldsRecognizedByJava())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .preflightFieldBoundary()
                .gateCreatesConnectionCommand())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .rollbackPathBoundary()
                .rollbackExecutionAllowedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary()
                .externalManagedAuditConnectionOpenedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .javaExecutionBoundary()
                .sqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .nodeMayTreatAsProductionAuditRecord())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .requiredPreflightFields())
        .containsExactly(
            "ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID",
            "ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE",
            "ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID",
            "ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID",
            "timeoutBudgetMs=15000",
            "ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT",
            "ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED");
    assertThat(
            headerBackedRehearsal.managedAuditSandboxConnectionPreflightEchoMarker().markerDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .readyForNodeV235ManualSandboxConnectionPreconditionIntake())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .receiptWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .consumedByNodeBlockedExecutionRehearsalProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-blocked-execution-rehearsal.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .ownerApprovalBoundary()
                .ownerApprovalArtifactRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .credentialBoundary()
                .credentialHandleReviewRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .schemaRehearsalBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .rollbackPathBoundary()
                .rollbackExecutionAllowedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .javaExecutionBoundary()
                .externalManagedAuditConnectionOpenedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .javaExecutionBoundary()
                .actualConnectionAttemptedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreconditionReceipt()
                .receiptDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .readyForNodeV237ManualSandboxConnectionReadinessGate())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .receiptWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .consumedByNodeDryRunRequestEnvelopeProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-dry-run-request-envelope.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .envelopeFieldBoundary()
                .operatorReviewFieldsComplete())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary()
                .credentialHandleOnly())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary()
                .credentialValueIncludedInEnvelope())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary()
                .actualConnectionAttemptedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary()
                .schemaMigrationSqlExecutedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .javaExecutionBoundary()
                .approvalLedgerWrittenByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionDryRunEnvelopeEchoReceipt()
                .receiptDigest())
        .startsWith("sha256:");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .readyForNodeV239ManualSandboxConnectionEvidenceVerification())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .receiptWarnings())
        .isEmpty();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .consumedByNodeOperatorWindowChecklistProfile())
        .isEqualTo("managed-audit-manual-sandbox-connection-operator-window-checklist.v1");
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .checklistFieldBoundary()
                .operatorChecklistReadOnly())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .approvalBoundary()
                .allApprovalItemsRequired())
        .isTrue();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .credentialBoundary()
                .credentialValueReadByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .javaExecutionBoundary()
                .actualConnectionAttemptedByJava())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .readyForManagedAuditSandboxAdapterConnection())
        .isFalse();
    assertThat(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorWindowChecklistEchoReceipt()
                .receiptDigest())
        .startsWith("sha256:");
    assertThat(headerBackedRehearsal.failureTaxonomy().upstreamReadiness()).isEqualTo("READY");
    assertThat(headerBackedRehearsal.failureTaxonomy().authContextReadiness()).isEqualTo("READY");
    assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationReadiness())
        .isEqualTo("READY");
    assertThat(headerBackedRehearsal.failureTaxonomy().authContextComplete()).isTrue();
    assertThat(headerBackedRehearsal.failureTaxonomy().auditCorrelationPresent()).isTrue();
    assertThat(headerBackedRehearsal.failureTaxonomy().failureCategories())
        .containsExactly("READ_ONLY_EXECUTION_BLOCKED");
    assertThat(headerBackedRehearsal.failureTaxonomy().taxonomyWarnings())
        .containsExactly("REHEARSAL_REMAINS_READ_ONLY");
    assertThat(headerBackedRehearsal.verificationHint().hintVersion())
        .isEqualTo("java-release-approval-rehearsal-verification-hint.v1");
    assertThat(headerBackedRehearsal.verificationHint().responseSchemaVersion())
        .isEqualTo("java-release-approval-rehearsal-response-schema.v52");
    assertThat(headerBackedRehearsal.verificationHint().warningDigest()).startsWith("sha256:");
    assertThat(headerBackedRehearsal.verificationHint().warningDigest())
        .isNotEqualTo(rehearsal.verificationHint().warningDigest());
    ReleaseApprovalRehearsalResponse repeatedHeaderBackedRehearsal =
        service.releaseApprovalRehearsal(headerBackedRehearsalRequest());
    assertThat(repeatedHeaderBackedRehearsal.verificationHint().warningDigest())
        .isEqualTo(headerBackedRehearsal.verificationHint().warningDigest());
    assertThat(
            repeatedHeaderBackedRehearsal
                .managedAuditAdapterImplementationGuardReceipt()
                .guardDigest())
        .isEqualTo(
            headerBackedRehearsal.managedAuditAdapterImplementationGuardReceipt().guardDigest());
    assertThat(
            repeatedHeaderBackedRehearsal
                .managedAuditExternalAdapterMigrationGuardReceipt()
                .guardDigest())
        .isEqualTo(
            headerBackedRehearsal.managedAuditExternalAdapterMigrationGuardReceipt().guardDigest());
    assertThat(
            repeatedHeaderBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .guardDigest())
        .isEqualTo(
            headerBackedRehearsal
                .managedAuditSandboxAdapterApprovalSchemaGuardReceipt()
                .guardDigest());
    assertThat(
            repeatedHeaderBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .markerDigest())
        .isEqualTo(
            headerBackedRehearsal
                .managedAuditSandboxConnectionOperatorHandoffMarker()
                .markerDigest());
    assertThat(
            repeatedHeaderBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .markerDigest())
        .isEqualTo(
            headerBackedRehearsal
                .managedAuditSandboxConnectionPreflightEchoMarker()
                .markerDigest());
    assertThat(headerBackedRehearsal.verificationHint().noLedgerWriteProved()).isTrue();
    assertThat(headerBackedRehearsal.verificationHint().nodeMayTreatAsProductionAuthorization())
        .isFalse();
    assertThat(headerBackedRehearsal.requestContext().operatorAuthenticatedByJava()).isFalse();
    assertThat(headerBackedRehearsal.requestContext().persistedByJava()).isFalse();
    assertThat(headerBackedRehearsal.requestContext().approvalLedgerWritten()).isFalse();
    assertThat(headerBackedRehearsal.executionAllowed()).isFalse();
    assertThat(headerBackedRehearsal.executionBoundaries().nodeMayWriteApprovalLedger()).isFalse();
  }
}
