package com.codexdemo.orderplatform;

import static org.hamcrest.Matchers.hasItem;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(properties = {
        "order.expiration.enabled=false",
        "outbox.publisher.enabled=false"
})
@AutoConfigureMockMvc
class OpsReleaseApprovalRehearsalAdapterGuardLiveAggregationIntegrationTests
        extends OpsReleaseApprovalRehearsalLiveAggregationIntegrationTestSupport {

    @Test
    void releaseApprovalRehearsalReturnsAdapterGuardReadOnlySignals() throws Exception {
        seedReleaseApprovalReplayApprovals();

        mockMvc.perform(get("/api/v1/ops/release-approval-rehearsal"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.receiptVersion")
                        .value("java-release-approval-rehearsal-managed-audit-adapter-implementation-guard-receipt.v1"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.sourceQualitySplitReceiptVersion")
                        .value("java-release-approval-rehearsal-ops-evidence-service-quality-split-receipt.v1"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.sourceQualitySplitSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v13"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.consumedByNodeDisabledShellVersion")
                        .value("Node v220"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.consumedByNodeDisabledShellProfile")
                        .value("managed-audit-adapter-disabled-shell.v1"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.consumedByNodeDisabledShellEndpoint")
                        .value("/api/v1/audit/managed-audit-adapter-disabled-shell"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.consumedByNodeDisabledShellState")
                        .value("disabled-shell-ready"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nextNodeCandidateVersion")
                        .value("Node v221"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nextNodeCandidateProfile")
                        .value("managed-audit-local-adapter-candidate-dry-run.v1"))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV221MayConsume")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220DisabledShellReady")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220SelectedAdapterDisabled")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220LocalDryRunOnlyDeclared")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220AppendWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220QueryReturnedRecords")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220ExternalManagedAuditAccessed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV220LocalDryRunWritePerformed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaApprovalDecisionCreated")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaApprovalLedgerWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaApprovalRecordPersisted")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaManagedAuditStoreWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaSqlExecuted")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaDeploymentTriggered")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaRollbackTriggered")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.javaRestoreExecuted")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.readyForNodeV221LocalAdapterCandidateDryRun")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.readyForProductionAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.readyForProductionWindow")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeMayTreatAsProductionAuditRecord")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.guardDigest").exists())
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.acceptedAdapterShellChecks",
                        hasItem("Node v220 selectedAdapterKind must stay disabled")))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.forbiddenImplementationOperations",
                        hasItem("Write approval ledger during Java v80 implementation guard")))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeV221Prerequisites",
                        hasItem("mini-kv v89 adapter shell non-storage guard receipt must be present before Node v221")))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.guardWarnings",
                        hasItem("NODE_V221_SOURCE_OPS_EVIDENCE_SERVICE_QUALITY_SPLIT_RECEIPT_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditAdapterImplementationGuardReceipt.nodeVerificationActions",
                        hasItem("Keep managedAuditAdapterImplementationGuardReceipt.nodeV220AppendWritten=false")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.receiptVersion")
                        .value("java-release-approval-rehearsal-managed-audit-external-adapter-migration-guard-receipt.v1"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.sourceImplementationGuardSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v14"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.consumedByNodeVerificationReportVersion")
                        .value("Node v222"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.consumedByNodeVerificationReportProfile")
                        .value("managed-audit-local-adapter-candidate-verification-report.v1"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.consumedByNodeVerificationReportEndpoint")
                        .value("/api/v1/audit/managed-audit-local-adapter-candidate-verification-report"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nextNodeReviewVersion")
                        .value("Node v223"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nextNodeReviewProfile")
                        .value("managed-audit-external-adapter-connection-readiness-review.v1"))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV223MayConsume")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV222VerificationReportReady")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV222ReadOnlyReport")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV222SourceEndpointRerunPerformed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV222AdditionalLocalDryRunWritePerformed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV222ConnectsManagedAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.ownerApprovalRequiredBeforeConnection")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.schemaMigrationReviewRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.credentialReviewRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.credentialValueReadByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.externalManagedAuditConnectionOpened")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.externalManagedAuditSchemaMigrated")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.javaApprovalLedgerWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.javaManagedAuditStoreWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.javaSqlExecuted")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.readyForNodeV223ExternalAdapterConnectionReadinessReview")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.readyForProductionAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.guardDigest").exists())
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.requiredPreConnectionReviews",
                        hasItem("external managed audit credential review")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.credentialBoundaryClaims",
                        hasItem("Java v81 must not read credential values")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.forbiddenExternalAdapterOperations",
                        hasItem("Execute schema migration SQL during Java v81 migration guard")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeV223Prerequisites",
                        hasItem("mini-kv v90 external adapter non-participation receipt must be present before Node v223")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.guardWarnings",
                        hasItem("NODE_V223_SOURCE_IMPLEMENTATION_GUARD_RECEIPT_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditExternalAdapterMigrationGuardReceipt.nodeVerificationActions",
                        hasItem("Keep managedAuditExternalAdapterMigrationGuardReceipt.externalManagedAuditConnectionOpened=false")))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.receiptVersion")
                        .value("java-release-approval-rehearsal-managed-audit-sandbox-adapter-approval-schema-guard-receipt.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.sourceExternalAdapterMigrationGuardSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v15"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.consumedByNodeSandboxPlanVersion")
                        .value("Node v224"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.consumedByNodeSandboxPlanProfile")
                        .value("managed-audit-sandbox-adapter-dry-run-plan.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.consumedByNodeSandboxPlanEndpoint")
                        .value("/api/v1/audit/managed-audit-sandbox-adapter-dry-run-plan"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nextNodePackageVersion")
                        .value("Node v225"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nextNodePackageProfile")
                        .value("managed-audit-sandbox-adapter-dry-run-package.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nodeV224SandboxPlan.readyForManagedAuditSandboxAdapterDryRunPlan")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nodeV224SandboxPlan.connectsManagedAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nodeV224SandboxPlan.readsManagedAuditCredential")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.ownerApprovalBoundary.ownerApprovalArtifactRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.ownerApprovalBoundary.ownerApprovalArtifactProvidedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.schemaRehearsalBoundary.schemaMigrationRehearsalRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.schemaRehearsalBoundary.schemaMigrationSqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.credentialBoundary.sandboxCredentialHandleRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.credentialBoundary.sandboxCredentialHandleName")
                        .value("ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE"))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.credentialBoundary.credentialValueReadByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.executionBoundary.externalManagedAuditConnectionOpened")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.executionBoundary.javaManagedAuditStoreWritten")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.executionBoundary.javaSqlExecuted")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.qualityGateBoundary.builderOrHelperSplitApplied")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.qualityGateBoundary.longBooleanConstructorAvoided")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.readyForNodeV225SandboxAdapterDryRunPackage")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.guardWarnings",
                        hasItem("NODE_V225_SOURCE_EXTERNAL_ADAPTER_MIGRATION_GUARD_RECEIPT_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.forbiddenSandboxOperations",
                        hasItem("Execute schema migration SQL during Java v82 guard")))
                .andExpect(jsonPath("$.managedAuditSandboxAdapterApprovalSchemaGuardReceipt.nodeV225Prerequisites",
                        hasItem("mini-kv v91 sandbox runtime evidence non-participation receipt must be present")))
                ;
    }
}
