package com.codexdemo.orderplatform;

import static org.hamcrest.Matchers.hasItem;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(properties = {
        "order.expiration.enabled=false",
        "outbox.publisher.enabled=false"
})
@AutoConfigureMockMvc
class OpsReleaseApprovalRehearsalLiveAggregationIntegrationTests
        extends OpsReleaseApprovalRehearsalLiveAggregationIntegrationTestSupport {
    @Test
    void releaseApprovalRehearsalReturnsReadOnlyLiveAggregation() throws Exception {
        seedReleaseApprovalReplayApprovals();

        mockMvc.perform(get("/api/v1/ops/release-approval-rehearsal"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.sampledAt").exists())
                .andExpect(jsonPath("$.rehearsalVersion").value("java-release-approval-rehearsal.v1"))
                .andExpect(jsonPath("$.sourceEvidenceEndpoint").value("/api/v1/ops/evidence"))
                .andExpect(jsonPath("$.rehearsalMode").value("READ_ONLY_RELEASE_APPROVAL_REHEARSAL"))
                .andExpect(jsonPath("$.readOnly").value(true))
                .andExpect(jsonPath("$.executionAllowed").value(false))
                .andExpect(jsonPath("$.requestContext.contextVersion")
                        .value("java-release-approval-rehearsal-context.v1"))
                .andExpect(jsonPath("$.requestContext.requestId")
                        .value("rehearsal-request-id-not-supplied"))
                .andExpect(jsonPath("$.requestContext.requestIdSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.requestContext.operatorIdentity")
                        .value("operator-identity-not-supplied"))
                .andExpect(jsonPath("$.requestContext.operatorIdentitySource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.requestContext.auditCorrelationId")
                        .value("audit-correlation-id-not-supplied"))
                .andExpect(jsonPath("$.requestContext.auditCorrelationSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.requestContext.operatorAuthenticatedByJava").value(false))
                .andExpect(jsonPath("$.requestContext.persistedByJava").value(false))
                .andExpect(jsonPath("$.requestContext.approvalLedgerWritten").value(false))
                .andExpect(jsonPath("$.requestContext.requiresProductionIdentityProvider").value(false))
                .andExpect(jsonPath("$.requestContext.acceptedReadOnlyHeaders",
                        hasItem("X-Rehearsal-Request-Id")))
                .andExpect(jsonPath("$.requestContext.acceptedReadOnlyHeaders",
                        hasItem("X-Operator-Identity")))
                .andExpect(jsonPath("$.requestContext.acceptedReadOnlyHeaders",
                        hasItem("X-Audit-Correlation-Id")))
                .andExpect(jsonPath("$.requestContext.contextWarnings",
                        hasItem("REHEARSAL_REQUEST_ID_MISSING")))
                .andExpect(jsonPath("$.requestContext.contextWarnings",
                        hasItem("OPERATOR_IDENTITY_MISSING")))
                .andExpect(jsonPath("$.requestContext.contextWarnings",
                        hasItem("AUDIT_CORRELATION_ID_MISSING")))
                .andExpect(jsonPath("$.operatorWindowHint.hintVersion")
                        .value("java-release-approval-rehearsal-operator-window-hint.v1"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorId")
                        .value("orderops-operator-id-not-supplied"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorIdSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorRoles")
                        .value("orderops-roles-not-supplied"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorRolesSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorVerifiedClaim")
                        .value("orderops-operator-verified-not-supplied"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorVerifiedClaimSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.operatorWindowHint.approvalCorrelationId")
                        .value("orderops-approval-correlation-id-not-supplied"))
                .andExpect(jsonPath("$.operatorWindowHint.approvalCorrelationIdSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.operatorWindowHint.operatorIdentityEchoed").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.operatorRolesEchoed").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.operatorVerifiedClaimEchoed").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.approvalCorrelationEchoed").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.operatorWindowContextComplete").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.productionIdpVerifiedByJava").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.persistedApprovalRecordByJava").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.nodeMayTreatAsProductionIdentity").value(false))
                .andExpect(jsonPath("$.operatorWindowHint.acceptedOperatorWindowHeaders",
                        hasItem("x-orderops-operator-id")))
                .andExpect(jsonPath("$.operatorWindowHint.acceptedOperatorWindowHeaders",
                        hasItem("x-orderops-approval-correlation-id")))
                .andExpect(jsonPath("$.operatorWindowHint.echoWarnings",
                        hasItem("ORDEROPS_OPERATOR_ID_MISSING")))
                .andExpect(jsonPath("$.operatorWindowHint.echoWarnings",
                        hasItem("ORDEROPS_APPROVAL_CORRELATION_ID_MISSING")))
                .andExpect(jsonPath("$.ciEvidenceHint.hintVersion")
                        .value("java-release-approval-rehearsal-ci-evidence-hint.v1"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestProfileVersion")
                        .value("ci-manifest-profile-version-not-supplied"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestProfileVersionSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestDigest")
                        .value("ci-manifest-digest-not-supplied"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestDigestSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestEndpoint")
                        .value("ci-manifest-endpoint-not-supplied"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestEndpointSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.ciEvidenceHint.artifactRecordCount")
                        .value("ci-artifact-record-count-not-supplied"))
                .andExpect(jsonPath("$.ciEvidenceHint.artifactRecordCountSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.ciEvidenceHint.approvalCorrelationId")
                        .value("ci-approval-correlation-id-not-supplied"))
                .andExpect(jsonPath("$.ciEvidenceHint.approvalCorrelationIdSource").value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestProfileVersionEchoed").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestDigestEchoed").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.manifestEndpointEchoed").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.artifactRecordCountEchoed").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.approvalCorrelationEchoed").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.ciEvidenceContextComplete").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.noLedgerWriteProof")
                        .value("NO_LEDGER_WRITE_PROOF_BY_RESPONSE_FIELDS"))
                .andExpect(jsonPath("$.ciEvidenceHint.noLedgerWriteProved").value(true))
                .andExpect(jsonPath("$.ciEvidenceHint.ciArtifactUploadedByJava").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.githubArtifactAccessedByJava").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.productionWindowAllowedByJava").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.nodeMayTreatAsCiArtifactPublication").value(false))
                .andExpect(jsonPath("$.ciEvidenceHint.acceptedCiEvidenceHeaders",
                        hasItem("x-orderops-ci-manifest-version")))
                .andExpect(jsonPath("$.ciEvidenceHint.acceptedCiEvidenceHeaders",
                        hasItem("x-orderops-ci-manifest-digest")))
                .andExpect(jsonPath("$.ciEvidenceHint.echoWarnings",
                        hasItem("ORDEROPS_CI_MANIFEST_VERSION_MISSING")))
                .andExpect(jsonPath("$.ciEvidenceHint.echoWarnings",
                        hasItem("ORDEROPS_CI_APPROVAL_CORRELATION_ID_MISSING")))
                .andExpect(jsonPath("$.artifactRetentionHint.hintVersion")
                        .value("java-release-approval-rehearsal-artifact-retention-hint.v1"))
                .andExpect(jsonPath("$.artifactRetentionHint.sourceRetentionFixtureVersion")
                        .value("java-release-audit-retention-fixture.v1"))
                .andExpect(jsonPath("$.artifactRetentionHint.sourceRetentionFixtureEndpoint")
                        .value("/contracts/release-audit-retention.fixture.json"))
                .andExpect(jsonPath("$.artifactRetentionHint.retentionId")
                        .value("release-retention-record-placeholder"))
                .andExpect(jsonPath("$.artifactRetentionHint.artifactTarget")
                        .value("release-tag-or-artifact-version-placeholder"))
                .andExpect(jsonPath("$.artifactRetentionHint.javaRetentionDays").value(180))
                .andExpect(jsonPath("$.artifactRetentionHint.ciUploadContractVersion")
                        .value("ci-upload-contract-version-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciUploadContractVersionSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciUploadContractDigest")
                        .value("ci-upload-contract-digest-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciArtifactName")
                        .value("ci-artifact-name-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciArtifactRoot")
                        .value("ci-artifact-root-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciRetentionDays")
                        .value("ci-retention-days-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.ciUploadMode")
                        .value("ci-upload-mode-not-supplied"))
                .andExpect(jsonPath("$.artifactRetentionHint.artifactRetentionContextComplete").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.retentionDaysWithinJavaRetention").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.javaRetentionFixtureReadOnly").value(true))
                .andExpect(jsonPath("$.artifactRetentionHint.auditExportReadOnly").value(true))
                .andExpect(jsonPath("$.artifactRetentionHint.ciArtifactUploadedByJava").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.githubArtifactAccessedByJava").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.productionWindowAllowedByJava").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.nodeMayTreatAsRetentionAuthorization").value(false))
                .andExpect(jsonPath("$.artifactRetentionHint.acceptedArtifactRetentionHeaders",
                        hasItem("x-orderops-ci-upload-contract-version")))
                .andExpect(jsonPath("$.artifactRetentionHint.acceptedArtifactRetentionHeaders",
                        hasItem("x-orderops-ci-retention-days")))
                .andExpect(jsonPath("$.artifactRetentionHint.releaseEvidenceEndpoints",
                        hasItem("/contracts/release-bundle-manifest.sample.json")))
                .andExpect(jsonPath("$.artifactRetentionHint.echoWarnings",
                        hasItem("ORDEROPS_CI_UPLOAD_CONTRACT_VERSION_MISSING")))
                .andExpect(jsonPath("$.artifactRetentionHint.echoWarnings",
                        hasItem("ORDEROPS_CI_RETENTION_DAYS_MISSING")))
                .andExpect(jsonPath("$.liveReadinessHint.hintVersion")
                        .value("java-release-approval-rehearsal-live-readiness-hint.v1"))
                .andExpect(jsonPath("$.liveReadinessHint.serverTimestamp").exists())
                .andExpect(jsonPath("$.liveReadinessHint.serverTimestampSource").value("sampledAt"))
                .andExpect(jsonPath("$.liveReadinessHint.readOnlyEndpointVersion")
                        .value("java-release-approval-rehearsal-response-schema.v43"))
                .andExpect(jsonPath("$.liveReadinessHint.readOnlyEndpoint")
                        .value("/api/v1/ops/release-approval-rehearsal"))
                .andExpect(jsonPath("$.liveReadinessHint.healthEndpoint").value("/actuator/health"))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightVersion")
                        .value("runtime-preflight-version-not-supplied"))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightVersionSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightDigest")
                        .value("runtime-preflight-digest-not-supplied"))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightDigestSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeSmokeSessionId")
                        .value("runtime-smoke-session-id-not-supplied"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeSmokeSessionIdSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeReadTargetId")
                        .value("runtime-read-target-id-not-supplied"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeReadTargetIdSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeWindowMode")
                        .value("runtime-window-mode-not-supplied"))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeWindowModeSource")
                        .value("NOT_SUPPLIED"))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightVersionEchoed").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.sourcePreflightDigestEchoed").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeSmokeSessionIdEchoed").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeReadTargetIdEchoed").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeWindowModeEchoed").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.liveReadinessContextComplete").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.readyForRuntimeSmokeRead").value(true))
                .andExpect(jsonPath("$.liveReadinessHint.readOnlyEndpointReady").value(true))
                .andExpect(jsonPath("$.liveReadinessHint.runtimeSmokeExecutedByJava").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.nodeMustRecordPidAndCleanup").value(true))
                .andExpect(jsonPath("$.liveReadinessHint.javaStartedProcessForNode").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.processCleanupRecordedByJava").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.nodeMayTreatAsProductionAuthorization").value(false))
                .andExpect(jsonPath("$.liveReadinessHint.acceptedLiveReadinessHeaders",
                        hasItem("x-orderops-runtime-preflight-version")))
                .andExpect(jsonPath("$.liveReadinessHint.acceptedLiveReadinessHeaders",
                        hasItem("x-orderops-runtime-smoke-session-id")))
                .andExpect(jsonPath("$.liveReadinessHint.allowedReadTargets",
                        hasItem("GET /actuator/health")))
                .andExpect(jsonPath("$.liveReadinessHint.allowedReadTargets",
                        hasItem("GET /api/v1/ops/release-approval-rehearsal")))
                .andExpect(jsonPath("$.liveReadinessHint.forbiddenRuntimeOperations",
                        hasItem("POST /api/v1/orders")))
                .andExpect(jsonPath("$.liveReadinessHint.forbiddenRuntimeOperations",
                        hasItem("Java process start/stop is owned by Node v205 smoke orchestration")))
                .andExpect(jsonPath("$.liveReadinessHint.echoWarnings",
                        hasItem("ORDEROPS_RUNTIME_PREFLIGHT_VERSION_MISSING")))
                .andExpect(jsonPath("$.liveReadinessHint.echoWarnings",
                        hasItem("ORDEROPS_RUNTIME_WINDOW_MODE_MISSING")))
                ;
    }
}
