package com.codexdemo.orderplatform;

import static org.hamcrest.Matchers.hasItem;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(properties = {
        "order.expiration.enabled=false",
        "outbox.publisher.enabled=false"
})
@AutoConfigureMockMvc
class OpsReleaseApprovalRehearsalSandboxConnectionLiveAggregationIntegrationTests
        extends OpsReleaseApprovalRehearsalLiveAggregationIntegrationTestSupport {

    @Test
    void releaseApprovalRehearsalReturnsSandboxConnectionReadOnlySignals() throws Exception {
        seedReleaseApprovalReplayApprovals();

        mockMvc.perform(get("/api/v1/ops/release-approval-rehearsal"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.markerVersion")
                        .value("java-release-approval-rehearsal-managed-audit-sandbox-connection-operator-handoff-marker.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.sourceSandboxAdapterApprovalSchemaGuardSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v16"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeEvidenceChecklistVersion")
                        .value("Node v227"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeEvidenceChecklistProfile")
                        .value("managed-audit-manual-sandbox-connection-evidence-checklist.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeOperatorPacketVersion")
                        .value("Node v228"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeOperatorPacketProfile")
                        .value("managed-audit-manual-sandbox-connection-operator-packet.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.consumedByNodeOperatorPacketEndpoint")
                        .value("/api/v1/audit/managed-audit-manual-sandbox-connection-operator-packet"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.nextNodePacketVerificationVersion")
                        .value("Node v229"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.nodeV229MayConsume")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.sandboxConnectionWindowBoundary.manualSandboxConnectionWindowRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.sandboxConnectionWindowBoundary.manualSandboxConnectionWindowOpenedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.sandboxConnectionWindowBoundary.connectionExecutionAllowed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.operatorPacketBoundary.ownerApprovalArtifactIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.operatorPacketBoundary.schemaRehearsalIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.operatorPacketBoundary.operatorPacketReadOnly")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.operatorPacketBoundary.ownerApprovalArtifactIdFieldRecognizedByJava")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.operatorPacketBoundary.packetCreatesApprovalDecision")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.credentialBoundary.credentialHandleNameField")
                        .value("ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.credentialBoundary.credentialValueReadByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.schemaRehearsalBoundary.schemaMigrationSqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.rollbackPathBoundary.rollbackPathIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.rollbackPathBoundary.manualAbortMarkerField")
                        .value("ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.rollbackPathBoundary.timeoutBudgetMs")
                        .value(15000))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.rollbackPathBoundary.rollbackExecutionAllowedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.javaExecutionBoundary.approvalLedgerWrittenByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.javaExecutionBoundary.externalManagedAuditConnectionOpenedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.javaExecutionBoundary.sqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.readyForNodeV229ManualSandboxConnectionPacketVerification")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.readyForManagedAuditSandboxAdapterConnection")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.readyForProductionAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.markerDigest").exists())
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.markerWarnings",
                        hasItem("NODE_V229_SOURCE_SANDBOX_ADAPTER_APPROVAL_SCHEMA_GUARD_RECEIPT_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionOperatorHandoffMarker.nodeV229Prerequisites",
                        hasItem("mini-kv v96 sandbox connection receipt echo marker must be ready")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.markerVersion")
                        .value("java-release-approval-rehearsal-managed-audit-sandbox-connection-preflight-echo-marker.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.sourceSandboxConnectionOperatorHandoffSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v17"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.consumedByNodePreflightGateVersion")
                        .value("Node v230"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.consumedByNodePreflightGateProfile")
                        .value("managed-audit-manual-sandbox-connection-preflight-gate.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.consumedByNodePreflightGateEndpoint")
                        .value("/api/v1/audit/managed-audit-manual-sandbox-connection-preflight-gate"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.consumedByNodePreflightGateState")
                        .value("manual-sandbox-connection-preflight-gate-ready"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.nextNodePreflightVerificationVersion")
                        .value("Node v231"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.nodeV231MayConsume")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.sandboxConnectionWindowBoundary.manualWindowFlagName")
                        .value("ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.sandboxConnectionWindowBoundary.manualWindowOpenByDefault")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.sandboxConnectionWindowBoundary.manualWindowOpenedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.sandboxConnectionWindowBoundary.nodeAutoStartAllowed")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.ownerApprovalArtifactIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.schemaRehearsalIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_SCHEMA_REHEARSAL_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.rollbackPathIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_ROLLBACK_PATH_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.timeoutBudgetMs")
                        .value(15000))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.manualAbortMarkerField")
                        .value("ORDEROPS_MANAGED_AUDIT_MANUAL_ABORT"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.allRequiredPreflightFieldsRecognizedByJava")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.preflightGateReadOnly")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.preflightFieldBoundary.gateCreatesConnectionCommand")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.credentialBoundary.credentialHandleNameField")
                        .value("ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.credentialBoundary.credentialValueReadByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.schemaRehearsalBoundary.schemaMigrationSqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.rollbackPathBoundary.rollbackExecutionAllowedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.javaExecutionBoundary.approvalLedgerWrittenByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.javaExecutionBoundary.externalManagedAuditConnectionOpenedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.javaExecutionBoundary.sqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.readyForNodeV231ManualSandboxConnectionPreflightVerification")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.readyForManagedAuditSandboxAdapterConnection")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.readyForProductionAudit")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.markerDigest").exists())
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.requiredPreflightFields",
                        hasItem("ORDEROPS_MANAGED_AUDIT_MANUAL_SANDBOX_WINDOW_APPROVED")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.markerWarnings",
                        hasItem("NODE_V231_SOURCE_SANDBOX_CONNECTION_OPERATOR_HANDOFF_MARKER_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreflightEchoMarker.nodeV231Prerequisites",
                        hasItem("mini-kv v97 no-start guard receipt must be ready")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.receiptVersion")
                        .value("java-release-approval-rehearsal-managed-audit-sandbox-connection-precondition-receipt.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.sourceSandboxConnectionPreflightEchoMarkerSchemaVersion")
                        .value("java-release-approval-rehearsal-response-schema.v18"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.consumedByNodeBlockedExecutionRehearsalVersion")
                        .value("Node v234"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.consumedByNodeBlockedExecutionRehearsalProfile")
                        .value("managed-audit-manual-sandbox-connection-blocked-execution-rehearsal.v1"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.nextNodePreconditionIntakeVersion")
                        .value("Node v235"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.ownerApprovalBoundary.ownerApprovalArtifactIdField")
                        .value("ORDEROPS_MANAGED_AUDIT_OWNER_APPROVAL_ARTIFACT_ID"))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.ownerApprovalBoundary.ownerApprovalArtifactRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.ownerApprovalBoundary.ownerApprovalArtifactProvidedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.credentialBoundary.credentialHandleReviewRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.credentialBoundary.credentialValueReadByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.schemaRehearsalBoundary.schemaMigrationSqlExecutedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.rollbackPathBoundary.timeoutBudgetMs")
                        .value(15000))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.rollbackPathBoundary.manualAbortMarkerRequired")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.javaExecutionBoundary.externalManagedAuditConnectionOpenedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.javaExecutionBoundary.actualConnectionAttemptedByJava")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.allPreconditionsDocumented")
                        .value(true))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.readyForNodeV235ManualSandboxConnectionPreconditionIntake")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.readyForManagedAuditSandboxAdapterConnection")
                        .value(false))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.receiptDigest").exists())
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.requiredPreconditionEvidence",
                        hasItem("credential handle review field: ORDEROPS_MANAGED_AUDIT_SANDBOX_CREDENTIAL_HANDLE")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.receiptWarnings",
                        hasItem("NODE_V235_SOURCE_SANDBOX_CONNECTION_PREFLIGHT_ECHO_MARKER_NOT_READY")))
                .andExpect(jsonPath("$.managedAuditSandboxConnectionPreconditionReceipt.nodeV235Prerequisites",
                        hasItem("mini-kv v100 current runtime fixture rolling evidence guard must be present")))
                .andExpect(jsonPath("$.failureTaxonomy.taxonomyVersion")
                        .value("java-release-approval-rehearsal-failure-taxonomy.v1"))
                .andExpect(jsonPath("$.failureTaxonomy.upstreamReadiness").value("READY"))
                .andExpect(jsonPath("$.failureTaxonomy.authContextReadiness").value("WARNING"))
                .andExpect(jsonPath("$.failureTaxonomy.auditCorrelationReadiness").value("WARNING"))
                .andExpect(jsonPath("$.failureTaxonomy.javaReadOnlyUpstreamReady").value(true))
                .andExpect(jsonPath("$.failureTaxonomy.authContextComplete").value(false))
                .andExpect(jsonPath("$.failureTaxonomy.auditCorrelationPresent").value(false))
                .andExpect(jsonPath("$.failureTaxonomy.retryableByReadOnlyAdapter").value(true))
                .andExpect(jsonPath("$.failureTaxonomy.writeActionRequired").value(false))
                .andExpect(jsonPath("$.failureTaxonomy.failureCategories",
                        hasItem("AUTH_CONTEXT_WARNING")))
                .andExpect(jsonPath("$.failureTaxonomy.failureCategories",
                        hasItem("AUDIT_CORRELATION_WARNING")))
                .andExpect(jsonPath("$.failureTaxonomy.failureCategories",
                        hasItem("READ_ONLY_EXECUTION_BLOCKED")))
                .andExpect(jsonPath("$.failureTaxonomy.taxonomyWarnings",
                        hasItem("REQUEST_ID_OR_OPERATOR_IDENTITY_MISSING")))
                .andExpect(jsonPath("$.failureTaxonomy.taxonomyWarnings",
                        hasItem("AUDIT_CORRELATION_ID_MISSING")))
                .andExpect(jsonPath("$.failureTaxonomy.taxonomyWarnings",
                        hasItem("REHEARSAL_REMAINS_READ_ONLY")));
    }
}
