create table failed_event_replay_approval_history (
    id bigint generated by default as identity primary key,
    failed_event_message_id bigint not null,
    action varchar(32) not null,
    operator_id varchar(80) not null,
    operator_role varchar(80) not null,
    note varchar(500),
    changed_at timestamp(6) with time zone not null,
    constraint fk_failed_event_replay_approval_history_message
        foreign key (failed_event_message_id) references failed_event_messages (id)
);

create index idx_failed_event_replay_approval_history_message
    on failed_event_replay_approval_history (failed_event_message_id, changed_at);

create index idx_failed_event_replay_approval_history_action
    on failed_event_replay_approval_history (action, changed_at);

create index idx_failed_event_replay_approval_history_operator_role
    on failed_event_replay_approval_history (operator_role, changed_at);

create index idx_failed_event_replay_approval_history_operator_id
    on failed_event_replay_approval_history (operator_id, changed_at);
