package com.codexdemo.orderplatform.ops.maintenance.readinesscore;

import java.util.List;

public record OpsShardReadinessDeclaredOperatorLifecycleResponse(
    String project,
    String version,
    boolean readOnly,
    boolean executionAllowed,
    boolean operatorOwned,
    boolean operatorLifecycleDeclared,
    boolean startupCommandDeclared,
    boolean portDeclared,
    boolean getOnlySmokeDeclared,
    boolean cleanupDeclared,
    boolean failClosedDeclared,
    boolean runtimeProbeAllowed,
    boolean nodeMayStartService,
    boolean nodeMayStopService,
    String sourceLifecycleEvidenceVersion,
    String lastVerifiedByNodeVersion,
    String nextNodeConsumerHint,
    String javaServiceOwner,
    String javaStartOwner,
    String javaStopOwner,
    String declaredWorkingDirectory,
    String declaredStartupCommand,
    List<String> declaredPorts,
    String javaBaseUrlHandle,
    List<String> getOnlySmokeTargets,
    List<String> failClosedRules,
    List<String> cleanupResponsibilities,
    List<String> runtimeGatePrerequisites,
    List<String> stopConditions,
    String evidencePath,
    String status) {}
