package com.codexdemo.orderplatform.ops.maintenance.v1contract;

import java.util.List;

public record OpsShardReadinessV1ContractConsumerReadinessHandoffResponse(
    String project,
    String version,
    String contractName,
    boolean readOnly,
    boolean executionAllowed,
    boolean shardEnabled,
    String readinessHandoffEndpoint,
    String readinessHandoffFixtureEndpoint,
    String evidenceDigestEndpoint,
    String evidenceDigestFixtureEndpoint,
    String evidenceDigestEvidencePath,
    String evidenceDigestReceiptId,
    int digestEvidenceCount,
    int digestCheckCount,
    List<String> digestEvidence,
    List<String> handoffGuardEvidence,
    List<String> handoffChecks,
    List<String> blockedOperations,
    boolean probesAreGetOnly,
    boolean upstreamActionsAllowed,
    boolean startsJavaService,
    boolean startsMiniKvService,
    boolean writeRoutingAllowed,
    boolean activeShardRouterAllowed,
    boolean credentialValueRead,
    boolean rawEndpointParsed,
    boolean managedAuditConnectionAllowed,
    boolean deploymentOrRollbackAllowed,
    boolean nodeMayStartOrStopJavaOrMiniKv,
    String receiptId,
    String evidencePath,
    String status) {}
